import assert from 'node:assert/strict';
import { createSpatialGrid } from '../src/world/spatial-grid.js';
import { scanBlindViewport } from '../src/world/blind-mundane/blind-mundane-scanner.js';
import { AdaptiveMundaneCache, adaptiveMundaneCacheKey, adaptiveMundaneResolution } from '../src/world/blind-mundane/adaptive-viewport-cache.js';
const DAY=86400000,ephemeris={id:'adaptive-fixture',planetLongitudes(date){const day=date.getTime()/DAY;return{Sun:(day*.9856)%360,Moon:(day*13.176)%360,Mercury:(day*1.2)%360,Mars:(day*.524)%360,Jupiter:(day*.083)%360,Saturn:(day*.033)%360,Uranus:(day*.012)%360,Neptune:(day*.006)%360,Pluto:(day*.004)%360}}},grid=createSpatialGrid(),date=new Date('2026-09-01T12:34:00Z');
assert.deepEqual([0,2.5,4.5,6.5,12].map(adaptiveMundaneResolution),[1,2,3,4,4]);
for(const resolution of [2,3,4]){const parent=grid.cellForLatLng(35.68,139.76,resolution),cellIds=grid.neighbors(parent,1),result=scanBlindViewport({startDate:date,ephemeris,grid,cellIds,horizonDays:30,limit:3});assert.equal(result.gridResolution,resolution);assert.equal(result.cells.length,cellIds.length);assert.ok(result.ranked.length>=1&&result.ranked.length<=3);assert.equal(result.selectionUsedObservations,false);assert.ok(result.cells.every(item=>item.cellId&&Number.isFinite(item.score)&&item.placeNameJa.endsWith('周辺')));assert.deepEqual(result,scanBlindViewport({startDate:date,ephemeris,grid,cellIds,horizonDays:30,limit:3}))}
assert.throws(()=>scanBlindViewport({startDate:date,ephemeris,grid,cellIds:[],horizonDays:30}),/must not be empty/);assert.throws(()=>scanBlindViewport({startDate:date,ephemeris,grid,cellIds:[grid.cellForLatLng(0,0,1)]}),/between 2 and 4/);assert.throws(()=>scanBlindViewport({startDate:date,ephemeris,grid,cellIds:[grid.cellForLatLng(0,0,2)],events:[]}),/rejects observational inputs/);
const key=adaptiveMundaneCacheKey({date,horizonDays:30,resolution:3,cellIds:['b','a']}),same=adaptiveMundaneCacheKey({date:new Date('2026-09-01T12:59:59Z'),horizonDays:30,resolution:3,cellIds:['a','b']});assert.equal(key,same);const cache=new AdaptiveMundaneCache(2);cache.set('a',1);cache.set('b',2);assert.equal(cache.get('a'),1);cache.set('c',3);assert.equal(cache.get('b'),null);assert.equal(cache.get('c'),3);
console.log('Adaptive mundane viewport scan passed');
