import assert from 'node:assert/strict';
import { EARTHQUAKE_OMEN_REGIONS, EARTH_SIGNS_VERSION, calculateEarthOmen, forecastEarthOmen, rankEarthOmens } from '../src/world/earth-signs-core.js';
import { loadOmenLedger, persistOmenLedger, saveOmenSnapshot, settleOmenEntries } from '../src/world/earth-signs-ledger.js';

const ephemeris={id:'fixture',planetLongitudes(date){const day=Math.floor(date.getTime()/86400000);return{Sun:(day*.9856)%360,Moon:(day*13.176)%360,Mars:(day*.524)%360,Saturn:(day*.033)%360,Uranus:(day*.012)%360,Pluto:(day*.004)%360}}},date=new Date('2026-09-01T00:00:00Z');
const quake=forecastEarthOmen({startDate:date,latitude:39,longitude:143,placeId:'jp-sanriku',placeNameJa:'岩手県沖から宮城県沖',category:'earthquake',ephemeris,horizonDays:7}),repeat=forecastEarthOmen({startDate:date,latitude:39,longitude:143,placeId:'jp-sanriku',placeNameJa:'岩手県沖から宮城県沖',category:'earthquake',ephemeris,horizonDays:7});
assert.equal(quake.engineVersion,EARTH_SIGNS_VERSION);assert.equal(quake.score,repeat.score);assert.equal(quake.reading,repeat.reading);assert.match(quake.reading,/岩手県沖から宮城県沖/);assert.match(quake.reading,/月\d+日/);assert.doesNotMatch(quake.reading,/断定|予言します/);
const volcano=forecastEarthOmen({startDate:date,latitude:32.88,longitude:131.1,placeId:'gvp-282110',placeNameJa:'阿蘇山周辺',category:'volcano',ephemeris,horizonDays:7});assert.match(volcano.reading,/火|地下|噴火/);assert.notEqual(volcano.reading,quake.reading);
const positions=ephemeris.planetLongitudes(date),before=calculateEarthOmen({date,latitude:35,longitude:140,category:'earthquake',positions}),after=calculateEarthOmen({date,latitude:35,longitude:140,category:'earthquake',positions});assert.deepEqual(before,after,'scientific observations cannot affect the astrology score');
const ranking=rankEarthOmens({places:EARTHQUAKE_OMEN_REGIONS.slice(0,8).map(item=>({...item,placeId:item.id,placeNameJa:item.nameJa})),startDate:date,category:'earthquake',ephemeris,horizonDays:7,limit:5});assert.equal(ranking.length,5);assert.ok(ranking.every((item,index)=>index===0||ranking[index-1].score>=item.score));assert.ok(ranking.every(item=>item.placeNameJa&&!/[0-9]+\.[0-9]+°/.test(item.placeNameJa)));
const memory=new Map(),storage={getItem:key=>memory.get(key)||null,setItem:(key,value)=>memory.set(key,value)},first=saveOmenSnapshot([quake,volcano],{storage}),second=saveOmenSnapshot([quake],{storage});assert.equal(first.added.length,2);assert.equal(second.added.length,0);assert.equal(loadOmenLedger(storage).length,2);
const evidence={earthquakes:[{id:'e1',datetimeUtc:quake.peakDate,latitude:39.1,longitude:143.1,magnitude:5.2}],observations:{thermalByVolcano:{'gvp-282110':{detectionCount:2,latestObservationUtc:volcano.peakDate}}}};const premature=settleOmenEntries(first.entries,{...evidence,asOf:new Date(quake.windowStart)});assert.ok(premature.every(item=>item.settlement.status==='pending'),'a forecast must remain pending until its window closes');const settled=settleOmenEntries(first.entries,{...evidence,asOf:'2027-01-01T00:00:00Z'});assert.equal(settled.find(item=>item.category==='earthquake').settlement.status,'overlap');assert.equal(settled.find(item=>item.category==='volcano').settlement.status,'overlap');persistOmenLedger(settled,{storage});assert.ok(loadOmenLedger(storage).every(item=>item.settlement.status==='overlap'),'settled results must persist');
console.log('Earth signs astrology and immutable ledger passed');
