import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import {
  EARTHQUAKE_FORECAST_FLAGS,EARTHQUAKE_SAFETY_NOTICE,LOCKED_VALIDATION,actionLevelFor,assertChronologicalSplit,
  buildBaselineFeatures,calculateDatedPreview,createForecastLayerState,createForecastUiModel,evaluateHoldoutRows,eventsAfterPreview,historyAvailableAt,peakDisplayMode,releaseGate,
  renderForecastShell,runBaselineModel,runDecayNeighborModel,validateForecastRow,validateLockedPeriods
} from '../src/world/earthquake-forecast/index.js';

const event=(datetimeUtc,id='event',cell_id='cell')=>({id,datetimeUtc,cell_id});

// AT01: forecast features may only use information strictly before forecast time.
assert.throws(()=>historyAvailableAt([event('2025-01-01T00:00:00Z')],'2025-01-01T00:00:00Z'),/future leakage blocked/);
assert.throws(()=>buildBaselineFeatures({events:[event('2025-01-02T00:00:00Z')],forecastTime:'2025-01-01T00:00:00Z',cellId:'cell'}),/future leakage blocked/);
const features=buildBaselineFeatures({events:[event('2024-12-01T00:00:00Z'),event('2024-12-30T00:00:00Z'),event('2024-12-31T00:00:00Z'),event('2024-12-31T00:00:00Z','other','other-cell')],forecastTime:'2025-01-01T00:00:00Z',cellId:'cell'});
assert.equal(features.latestSourceTimeUtc,'2024-12-31T00:00:00.000Z');assert.equal(features.recentCount7d,2);
assert.equal(features.historyCount,3,'baseline history must remain scoped to one H3 cell');assert.throws(()=>buildBaselineFeatures({events:[],forecastTime:'2025-01-01T00:00:00Z'}),/cellId is required/);

// AT02: chronological periods are frozen and non-overlapping.
assert.equal(validateLockedPeriods(),true);assert.deepEqual(LOCKED_VALIDATION.development,['2005-01-01','2014-12-31']);assert.deepEqual(LOCKED_VALIDATION.holdout,['2015-01-01','2025-12-31']);
assert.throws(()=>validateLockedPeriods({development:['2006-01-01','2014-12-31'],holdout:['2015-01-01','2025-12-31']}),/must not change/);
const split=assertChronologicalSplit([event('2005-01-01T00:00:00Z')],[event('2025-12-31T23:59:59Z')]);assert.equal(split.development.length,1);assert.equal(split.holdout.length,1);

// Baseline is deterministic and contains only background/recent-rate factors.
const baseline=runBaselineModel(features,7);assert.ok(baseline.backgroundProbability>0&&baseline.backgroundProbability<1);assert.ok(baseline.modelProbability>0&&baseline.modelProbability<1);assert.deepEqual(baseline.topFactors,['背景活動率','直近7日活動率','直近30日活動率']);
for(const forbidden of ['潮汐','b値','天体','地磁気'])assert.ok(!baseline.topFactors.some(item=>item.includes(forbidden)));
const quietCandidate=runDecayNeighborModel({targetBackgroundDailyRate:.0001,nearbyEvents:[]},7),recentCandidate=runDecayNeighborModel({targetBackgroundDailyRate:.0001,nearbyEvents:[{ageDays:1,ring:0,magnitude:6.5}]},7),oldCandidate=runDecayNeighborModel({targetBackgroundDailyRate:.0001,nearbyEvents:[{ageDays:30,ring:0,magnitude:6.5}]},7),distantCandidate=runDecayNeighborModel({targetBackgroundDailyRate:.0001,nearbyEvents:[{ageDays:1,ring:2,magnitude:6.5}]},7);assert.ok(recentCandidate.modelProbability>quietCandidate.modelProbability);assert.ok(recentCandidate.modelProbability>oldCandidate.modelProbability);assert.ok(recentCandidate.modelProbability>distantCandidate.modelProbability);assert.ok(recentCandidate.topFactors.every(item=>!/(潮汐|天体|地磁気)/.test(item)));
const compactCatalog={latestTimeUtcMs:Date.parse('2021-01-01T00:00:00Z'),eventsByCell:{cell:[[Date.parse('2006-01-01T00:00:00Z'),4.6],[Date.parse('2007-01-01T00:00:00Z'),5.1],[Date.parse('2008-01-01T00:00:00Z'),6.6],[Date.parse('2020-12-20T00:00:00Z'),6.8]]}},beforeFuture=calculateDatedPreview(compactCatalog,{forecastTime:'2015-01-01T00:00:00Z',targetMagnitude:6.5,horizonDays:30}),withoutFuture=calculateDatedPreview({...compactCatalog,eventsByCell:{cell:compactCatalog.eventsByCell.cell.slice(0,3)}},{forecastTime:'2015-01-01T00:00:00Z',targetMagnitude:6.5,horizonDays:30}),afterFuture=calculateDatedPreview(compactCatalog,{forecastTime:'2021-01-01T00:00:00Z',targetMagnitude:6.5,horizonDays:30}),futureClamped=calculateDatedPreview(compactCatalog,{forecastTime:'2030-01-01T00:00:00Z',targetMagnitude:4.5,horizonDays:7});assert.deepEqual(beforeFuture.rows,withoutFuture.rows,'events after the selected date must not affect recalculation');assert.notEqual(beforeFuture.rows[0].preview_value,afterFuture.rows[0].preview_value,'changing the selected date must recalculate the preview');assert.equal(futureClamped.futureDateClamped,true);assert.equal(futureClamped.calculationTimeUtc,'2021-01-01T00:00:00.000Z');
const outcomeCatalog={latestTimeUtcMs:Date.parse('2020-02-01T00:00:00Z'),eventsByCell:{A:[[Date.parse('2020-01-02T00:00:00Z'),4.7,35,140],[Date.parse('2020-01-10T00:00:00Z'),6.7,36,141],[Date.parse('2020-01-20T00:00:00Z'),7,37,142]]}},m45Outcomes=eventsAfterPreview(outcomeCatalog,{forecastTime:'2020-01-01T00:00:00Z',targetMagnitude:4.5,horizonDays:14}),m65Outcomes=eventsAfterPreview(outcomeCatalog,{forecastTime:'2020-01-01T00:00:00Z',targetMagnitude:6.5,horizonDays:14});assert.equal(m45Outcomes.length,2);assert.deepEqual(m65Outcomes.map(item=>item.magnitude),[6.7]);assert.equal(m65Outcomes[0].latitude,36);assert.ok(m65Outcomes.every(item=>item.time_utc<'2020-01-15T00:00:00.000Z'));

// AT03 and AT06: predictive display and every unvalidated modifier default off.
assert.equal(EARTHQUAKE_FORECAST_FLAGS.earthquakeForecastEnabled,true);for(const key of ['experimentalPredictiveUIEnabled','actionLevel1Enabled','actionLevel2Enabled','peakDateEnabled','tidalModifierEnabled','bValueStaticStateEnabled','celestialModifierEnabled'])assert.equal(EARTHQUAKE_FORECAST_FLAGS[key],false,`${key} must default off`);

const passingMetrics={n_holdout_rows:1000,n_target_events:60,background_logloss:.6,model_logloss:.5,background_brier:.2,model_brier:.18,information_gain_nats_per_row:.1,event_recall:.5,alert_precision:.3,false_alert_fraction:.08,space_time_alarm_fraction:.05,alert_day_fraction:.06,median_lead_days:2,peak_window_hit_rate:.6,topk_region_recall:.5};
const realHoldout={realHoldout:true,validationVersion:'2.8.0',dataset:{development_start:'2005-01-01',development_end:'2014-12-31',holdout_start:'2015-01-01',holdout_end:'2025-12-31',target_magnitude_threshold:6.5},sourceManifest:{provider:'GCMT',sha256:'a'.repeat(64),recordCount:1000},horizons:LOCKED_VALIDATION.horizonsDays.map(horizon_days=>({horizon_days,...passingMetrics}))};
const defaultGate=releaseGate(realHoldout);assert.equal(defaultGate.allowed,false);assert.equal(defaultGate.reason,'predictive-ui-disabled');assert.equal(defaultGate.bestHorizonDays,1);
const releaseFlags={...EARTHQUAKE_FORECAST_FLAGS,experimentalPredictiveUIEnabled:true};assert.equal(releaseGate(realHoldout,releaseFlags).allowed,true);
const noSourceGate=releaseGate({...realHoldout,sourceManifest:null},releaseFlags);assert.equal(noSourceGate.allowed,false);assert.equal(noSourceGate.reason,'real-holdout-required');

// AT07: a noisy or baseline-inferior model cannot pass the display gate.
const noisy={...realHoldout,horizons:realHoldout.horizons.map(item=>({...item,model_logloss:.7,information_gain_nats_per_row:-.1}))};assert.equal(releaseGate(noisy,releaseFlags).allowed,false);
const onlySeven={...realHoldout,horizons:realHoldout.horizons.map(item=>item.horizon_days===7?{...item,information_gain_nats_per_row:.2}:{...item,model_logloss:.7,information_gain_nats_per_row:-.1})},sevenGate=releaseGate(onlySeven,releaseFlags);assert.equal(sevenGate.allowed,true);assert.equal(sevenGate.bestHorizonDays,7);assert.deepEqual(sevenGate.passingHorizonDays,[7]);assert.equal(sevenGate.horizonDecisions[3].passed,false);
const allFailGate=releaseGate(noisy,releaseFlags);assert.equal(allFailGate.allowed,false);assert.equal(allFailGate.bestHorizonDays,null);assert.deepEqual(allFailGate.passingHorizonDays,[]);
const tieBreak={...realHoldout,horizons:realHoldout.horizons.map(item=>({...item,information_gain_nats_per_row:item.horizon_days===3||item.horizon_days===7?.3:.1,space_time_alarm_fraction:item.horizon_days===7?.02:.05}))};assert.equal(releaseGate(tieBreak,releaseFlags).bestHorizonDays,7,'equal information gain must prefer lower alert burden');

const holdoutRow=(day,{cell_id='cell',outcome=0,alert=false,backgroundProbability=.1,modelProbability=.1,...rest}={})=>({forecast_time_utc:`2020-01-${String(day).padStart(2,'0')}T00:00:00Z`,cell_id,outcome,alert,backgroundProbability,modelProbability,...rest});
const threeDayHit=evaluateHoldoutRows([holdoutRow(1,{alert:true,modelProbability:.7}),holdoutRow(4,{outcome:1,modelProbability:.7,peakHit:true,regionRank:1})],{horizonDays:7});assert.equal(threeDayHit.event_recall,1);assert.equal(threeDayHit.alert_precision,1);assert.equal(threeDayHit.median_lead_days,3);
const outsideHorizon=evaluateHoldoutRows([holdoutRow(1,{alert:true}),holdoutRow(9,{outcome:1})],{horizonDays:7});assert.equal(outsideHorizon.event_recall,0);assert.equal(outsideHorizon.alert_precision,0);assert.equal(outsideHorizon.false_alert_share,1);
const episodeMetrics=evaluateHoldoutRows([holdoutRow(1,{alert:true}),holdoutRow(2,{alert:true}),holdoutRow(3,{alert:true}),holdoutRow(5,{outcome:1})],{horizonDays:7});assert.equal(episodeMetrics.n_alert_episodes,1,'consecutive alert days must form one episode');assert.equal(episodeMetrics.alert_precision,1);assert.equal(episodeMetrics.space_time_alarm_fraction,.75);assert.equal(episodeMetrics.alert_day_fraction,.75);
const neighborHit=evaluateHoldoutRows([holdoutRow(1,{cell_id:'A',alert:true}),holdoutRow(3,{cell_id:'B',outcome:1})],{horizonDays:7,allowedNeighborCells:{A:['B']}});assert.equal(neighborHit.event_recall,1,'a pre-frozen allowed neighboring H3 cell may match');

// AT04: model output can never produce Level 3; only official information can.
const actionFlags={...EARTHQUAKE_FORECAST_FLAGS,actionLevel1Enabled:true,actionLevel2Enabled:true};assert.equal(actionLevelFor({riskScore:100,displayAllowed:true},actionFlags),2);assert.equal(actionLevelFor({riskScore:100,displayAllowed:true,officialInformation:true},actionFlags),2);assert.equal(actionLevelFor({riskScore:100,displayAllowed:true,officialInformation:{active:true,provider:'unverified'}},actionFlags),2);assert.equal(actionLevelFor({riskScore:100,displayAllowed:true,officialInformation:{active:true,provider:'JMA'}},actionFlags),3);assert.equal(actionLevelFor({riskScore:100,displayAllowed:false},actionFlags),0);

// AT08: peak date is downgraded unless both flag and locked-holdout threshold pass.
assert.equal(peakDisplayMode({peak_window_hit_rate:1}), 'window');assert.equal(peakDisplayMode({peak_window_hit_rate:.54},{...EARTHQUAKE_FORECAST_FLAGS,peakDateEnabled:true}),'window');assert.equal(peakDisplayMode({peak_window_hit_rate:.55},{...EARTHQUAKE_FORECAST_FLAGS,peakDateEnabled:true}),'date');

const row=validateForecastRow({forecast_time_utc:'2026-01-01T00:00:00Z',cell_id:'cell',region_name:'東京',horizon_days:7,risk_score_0_100:72,confidence_0_100:60,action_level:1,forecast_window_start_utc:'2026-01-01T00:00:00Z',forecast_window_end_utc:'2026-01-08T00:00:00Z',rise_start_utc:null,historical_precision:.3,historical_recall:.5,median_lead_days:2,data_quality:.8,top_factors:['背景活動率'],model_version:'model',validation_version:'2.8.0'});
assert.equal(row.risk_score_0_100,72);assert.ok(Object.isFrozen(row));
assert.throws(()=>validateForecastRow({...row,action_level:3}),/verified official information/);
assert.throws(()=>validateForecastRow({...row,forecast_window_end_utc:'2026-01-09T00:00:00Z'}),/match horizon_days/);

// AT05 and AT09: score is not probability, and official-information priority is always present.
const hiddenModel=createForecastUiModel({releaseResult:realHoldout,row});assert.equal(hiddenModel.visible,false);assert.equal(renderForecastShell(hiddenModel),'');
const visibleModel=createForecastUiModel({releaseResult:realHoldout,row},releaseFlags),html=renderForecastShell(visibleModel);assert.ok(html.includes('相対リスク指標 72 / 100'));assert.ok(!/発生確率\s*72|72\s*%/.test(html));assert.ok(html.includes(EARTHQUAKE_SAFETY_NOTICE));assert.match(EARTHQUAKE_SAFETY_NOTICE,/気象庁・自治体等の公式情報を優先/);
const failedHorizonModel=createForecastUiModel({releaseResult:onlySeven,row:{...row,horizon_days:3}},releaseFlags);assert.equal(failedHorizonModel.visible,false,'a failed horizon must never reach predictive UI');assert.equal(renderForecastShell(failedHorizonModel),'');

const pendingLayer=createForecastLayerState();assert.equal(pendingLayer.status,'検証中');assert.equal(pendingLayer.realHoldoutStatus,'未実施');assert.equal(pendingLayer.predictiveUiEnabled,false);assert.deepEqual(pendingLayer.horizonCandidates,[1,3,7,14,30]);assert.equal(pendingLayer.allowedRows.length,0);assert.equal(pendingLayer.modelName,'背景活動率・直近活動率ベースライン v1');
const disabledLayer=createForecastLayerState({releaseResult:onlySeven,rows:[{cell_id:'cell',horizon_days:7,risk_score_0_100:72},{cell_id:'cell',horizon_days:3,risk_score_0_100:99}]});assert.equal(disabledLayer.predictiveUiEnabled,false);assert.equal(disabledLayer.allowedRows.length,0,'forecast values must remain unavailable while the predictive flag is off');
const releasedLayer=createForecastLayerState({releaseResult:onlySeven,rows:[{cell_id:'cell',horizon_days:7,risk_score_0_100:72},{cell_id:'cell',horizon_days:3,risk_score_0_100:99}]},releaseFlags);assert.equal(releasedLayer.predictiveUiEnabled,true);assert.equal(releasedLayer.bestHorizonDays,7);assert.deepEqual(releasedLayer.allowedRows,[{cell_id:'cell',horizon_days:7,risk_score_0_100:72}]);

// AT10: existing World globe, bottom sheet and six-item mobile navigation remain untouched.
const [app,mapUi,mapCss,worker]=await Promise.all(['../app.html','../src/world/world-map-ui.js','../src/world/world-map.css','../service-worker.js'].map(path=>readFile(new URL(path,import.meta.url),'utf8')));
const mobileNav=app.match(/<nav class="mobile-nav"[\s\S]*?<\/nav>/)?.[0]||'';assert.equal((mobileNav.match(/<button/g)||[]).length,6);assert.ok(mapUi.includes("map.setProjection({type:'globe'})"));assert.ok(mapUi.includes('world-sheet'));assert.ok(mapCss.includes('.world-sheet'));assert.ok(mapCss.includes('min-height:44px')||app.includes('min-height:46px'));assert.ok(mapCss.includes('pointer-events:none'),'validation notice must not block globe cell taps');
for(const token of ['maxZoom:14','forecastLayerOn?2:null','forecastLayerOn?2:grid.resolutionForZoom','cluster:true','clusterMaxZoom:6',"14,.5"] )assert.ok(mapUi.includes(token),`${token} must preserve forecast resolution while enabling deeper zoom`);
assert.ok(!app.includes('earthquake-forecast'),'predictive values must not be mounted directly in the app shell');assert.ok(mapUi.includes("createForecastLayerState"),'World map must route earthquake prediction through the release-gated state');for(const token of ['earthquakeForecastLayer','研究プレビュー・検証中','earthquakePreviewHorizon','realHoldoutExecuted!==false'])assert.ok(mapUi.includes(token),`${token} must protect the World forecast layer`);for(const forbidden of ['risk_score_0_100','action_level','peak date'])assert.ok(!mapUi.includes(forbidden),`${forbidden} must not enter the research preview DOM`);
for(const asset of ['index.js','config.js','types.js','data.js','features.js','model.js','validation.js','display-policy.js','action-policy.js','ui.js'])assert.ok(worker.includes(`./src/world/earthquake-forecast/${asset}`),`${asset} must be cached offline`);
assert.ok(worker.includes('./data/world/earthquake-research-preview-v1.json'),'fixed preview must be cached offline');
assert.ok(worker.includes('./data/world/earthquake-research-catalog-v2.json'),'dated preview catalog must be cached offline');

const preview=JSON.parse(await readFile(new URL('../data/world/earthquake-research-preview-v1.json',import.meta.url),'utf8'));assert.equal(preview.schemaId,'koyomi-earthquake-research-preview-v1');assert.equal(preview.realHoldoutExecuted,false);assert.equal(preview.bandMethod,'target-specific-all-horizon-fixed-quantiles-v1');assert.deepEqual(preview.horizonsDays,[1,3,7,14,30]);assert.ok(preview.recordCount>100000);assert.ok(preview.rows.length>10000);assert.ok(preview.sources.every(source=>/^[a-f0-9]{64}$/.test(source.sha256)&&source.recordCount>0));for(const target of [4.5,6.5])for(const horizon of preview.horizonsDays)assert.ok(preview.rows.some(row=>row.target_magnitude===target&&row.horizon_days===horizon));
assert.deepEqual(preview.targetMagnitudes,[4.5,6.5]);assert.equal(preview.defaultTargetMagnitude,6.5);assert.deepEqual(preview.developmentApprovedHorizons,{'4.5':[],'6.5':[30]});assert.ok(preview.rows.filter(row=>row.target_magnitude===6.5&&row.horizon_days===30).every(row=>row.model_tier==='development-approved'));assert.ok(preview.rows.filter(row=>row.target_magnitude===4.5).every(row=>row.model_tier==='research-activity'));for(const token of ['earthquakePreviewMagnitude','M4.5以上・活動度','M6.5以上・大地震注意度','<option selected>30</option>'])assert.ok(mapUi.includes(token),`${token} must support magnitude switching`);
const sampleCell=preview.rows[0].cell_id,bands=preview.rows.filter(row=>row.cell_id===sampleCell&&row.target_magnitude===4.5).map(row=>row.relative_band);assert.ok(new Set(bands).size>1,'horizon switch must be capable of changing the fixed-band display');
const development=JSON.parse(await readFile(new URL('../data/research/earthquake-development-evaluation-v2.json',import.meta.url),'utf8'));assert.equal(development.realHoldoutExecuted,false);assert.deepEqual(development.results.filter(result=>result.developmentPassed).map(result=>result.horizonDays),[30]);const approvedDevelopment=development.results.find(result=>result.horizonDays===30);assert.ok(approvedDevelopment.confirmation.informationGain>0);assert.ok(approvedDevelopment.confirmation.brierImprovement>0);assert.ok(approvedDevelopment.yearly.every(year=>year.informationGain>0));
const datedCatalog=JSON.parse(await readFile(new URL('../data/world/earthquake-research-catalog-v2.json',import.meta.url),'utf8'));assert.equal(datedCatalog.schemaId,'koyomi-earthquake-research-catalog-v2');assert.ok(Object.keys(datedCatalog.eventsByCell).length>1000);assert.ok(Object.values(datedCatalog.eventsByCell).reduce((sum,items)=>sum+items.length,0)>100000);assert.ok(Object.values(datedCatalog.eventsByCell).flat().every(item=>item.length===9&&item.slice(0,5).every(Number.isFinite)&&typeof item[5]==='string'&&Number.isFinite(item[6])&&typeof item[7]==='string'&&typeof item[8]==='string'));assert.equal(datedCatalog.freshness.complete,true);assert.equal(datedCatalog.freshness.expectedRecords,datedCatalog.freshness.storedRecords);assert.equal(datedCatalog.inputSha256,createHash('sha256').update(JSON.stringify(datedCatalog.eventsByCell)).digest('hex'));assert.equal(preview.inputCatalog.sha256,datedCatalog.inputSha256);for(const token of ['calculateDatedPreview','recalculatePreview','futureDateClamped','計算基準日','earthquakeOutcomeLayer','forecast-outcome-dots','期間内の実績','予測計算に使用していない事後確認データ','カタログ収録終了','最終更新成功','完全性確認','inputSha256'])assert.ok(mapUi.includes(token),`${token} must support dated recalculation, outcome comparison, and freshness`);

console.log('Earthquake forecast v2.8 safety acceptance passed: AT01-AT10');
