import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { buildGvpCatalog, normalizeGvpFeature } from '../scripts/update-gvp-volcano-catalog.mjs';
import { volcanoGeoJson } from '../src/world/volcano/map-layer.js';

const fixture=index=>({type:'Feature',geometry:{type:'Point',coordinates:[130+(index%20)*.1,30+(index%10)*.1]},properties:{Volcano_Number:200000+index,Volcano_Name:`Volcano ${index}`,Latitude:30+(index%10)*.1,Longitude:130+(index%20)*.1,Elevation:1000,Country:'Fixture',Region:'Test Arc',Primary_Volcano_Type:'Stratovolcano',Evidence_Category:'Eruption Dated'}});
assert.equal(normalizeGvpFeature({properties:{}}),null);const catalog=buildGvpCatalog({features:Array.from({length:1001},(_,index)=>fixture(index))},{generatedAt:'2026-08-28T00:00:00Z'});assert.equal(catalog.volcanoes.length,1001);assert.match(catalog.sha256,/^[a-f0-9]{64}$/);assert.throws(()=>buildGvpCatalog({features:[fixture(1)]}),/unexpectedly small/);
const real=JSON.parse(await readFile(new URL('../data/world/volcano-catalog-v2.json',import.meta.url),'utf8'));assert.equal(real.schemaId,'koyomi-volcano-catalog-v2');assert.equal(real.volcanoes.length,1214);assert.equal(new Set(real.volcanoes.map(item=>item.gvpNumber)).size,1214);assert.ok(real.volcanoes.every(item=>Number.isFinite(item.latitude)&&Number.isFinite(item.longitude)&&item.sourceUrl.includes(String(item.gvpNumber))));
const id=real.volcanoes[0].id,observations={thermalByVolcano:{[id]:{status:'available',totalFrpMw:120,detectionCount:4,multiSensorConfirmed:true}}},confirmation=volcanoGeoJson(real,observations,'confirmation'),frp=volcanoGeoJson(real,observations,'frp');assert.equal(confirmation.features.length,1214);assert.equal(confirmation.features[0].properties.heatBand,4);assert.equal(frp.features[0].properties.heatBand,4);assert.equal(volcanoGeoJson(real,null).features[0].properties.heatBand,0);
const layer=await readFile(new URL('../src/world/volcano/map-layer.js',import.meta.url),'utf8'),ui=await readFile(new URL('../src/world/world-map-ui.js',import.meta.url),'utf8'),workflow=await readFile(new URL('../.github/workflows/update-volcano-observations.yml',import.meta.url),'utf8');for(const token of ['clusterProperties','maxAlertBand','observationActiveCount','multiSensorConfirmed','totalFrpMw'])assert.ok(layer.includes(token),token);for(const token of ['世界の火山・公的警戒レイヤー','観測確認度','実測熱量（FRP）','噴火危険度ではありません'])assert.ok(ui.includes(token),token);assert.ok(workflow.includes('update-gvp-volcano-catalog.mjs'));
console.log('Global 1214-volcano thermal map passed');
