import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const app = await readFile('app.html', 'utf8');
const smoke = await readFile('smoke-test.html', 'utf8');
const index = await readFile('index.html', 'utf8');
const today = await readFile('today.html', 'utf8');

assert.ok(app.includes('koyomiEditOwnProfile'), 'own profile edit route must remain present');
assert.ok(app.includes('koyomiApplyPrimaryProfile'), 'primary profile selection must remain present');
assert.ok(app.includes('visualViewport') || app.includes('VisualViewport'), 'mobile viewport handling must remain present');
assert.ok(app.includes('KOYOMI_BAZI'), 'Bazi module hook must be present');
assert.ok(smoke.includes('bazi engine module'), 'smoke test must include Bazi module check');
assert.ok(index.includes('app.html') || index.includes('today.html'), 'index navigation must remain present');
assert.ok(!index.includes('KOYOMIの約束'),'home must not show nonessential explanatory copy');
assert.ok(!app.includes('迷ったら本鑑定へ。'),'app home must not repeat guidance before the main choice');
assert.ok(!app.includes('四柱推命を主軸に、宿曜・九星'),'pre-reading screen must not list every divination method');
assert.ok(app.includes('<summary>話し方を選ぶ</summary>'),'optional voice settings must use progressive disclosure');
assert.ok(today.includes('<h1>今日の暦</h1>'), 'today page must remain present');
assert.ok(app.includes('id="koyomiChoosePerson"'), 'home must provide a person-based reading entry');
assert.ok(app.includes('id="koyomiChooseTheme"'), 'home must provide a theme-based reading entry');
assert.ok(app.includes("$('koyomiChoosePerson').onclick=koyomiOpenPersonPicker"), 'person entry must open the profile selector');
assert.ok(app.includes('id="koyomiThemePanel"'), 'theme entry must reveal a theme choice panel');
assert.equal((app.match(/choices:\[\[/g)||[]).length,5,'first concern step must offer at most five choices');
assert.ok(app.includes('koyomiRenderConcernChoices'),'concern selection must use progressive disclosure');
assert.ok(app.includes('data-koyomi-back'),'second concern step must allow going back');
assert.ok(app.includes("$('qFocus').value=focus"), 'theme choice must update the detailed focus');
assert.ok(app.includes("$('theme').value=category"), 'theme choice must update the broad category');
assert.ok(app.includes("await ledgerOpenSelector('personal')"),'concern selection must continue to person selection');
assert.ok(app.includes('id="koyomiOpenResult"'), 'home must provide a previous-result entry');
assert.ok(app.includes('id="koyomiChooseReadingDate"'), 'home must provide a date-specific reading entry');
assert.ok(app.indexOf('id="koyomiStartReading"') < app.indexOf('id="koyomiChooseReadingDate"'), 'date-specific reading must appear below today reading');
assert.ok(app.includes('id="koyomiReadingDate" type="date"'), 'date-specific reading must use a date picker');
assert.ok(app.includes('selectedDate=startOfDay(date);renderCalendar()'), 'selected date must update the existing reading date before calculation');
assert.ok(app.includes("['koyomiStartReading','koyomiStartDateReading']"), 'selected-date reading must refresh the structured reading output');
const mobileNav=app.match(/<nav class="mobile-nav"[\s\S]*?<\/nav>/)?.[0]||'';
assert.equal((mobileNav.match(/<button/g)||[]).length,5,'SOL mobile navigation must contain exactly five primary destinations');
for(const label of ['今日','占う','記録','暦','設定'])assert.ok(mobileNav.includes(label),`${label} must remain in mobile navigation`);
assert.ok(!mobileNav.includes('data-page="qimen"'),'specialist methods must move out of primary navigation');
assert.ok(!mobileNav.includes('data-page="mundane"'),'mundane must move out of primary navigation');
assert.ok(app.includes("nav.querySelector('[data-page=\"personal\"]').onclick=()=>koyomiOpenMobilePage('personal')"),'mobile reading button must have an explicit route');
assert.ok(app.includes("nav.querySelector('[data-page=\"ledger\"]').onclick=()=>koyomiOpenMobilePage('ledger')"),'mobile person button must have an explicit route');
assert.ok(app.includes("nav.querySelector('[data-page=\"settings\"]').onclick=()=>koyomiOpenMobilePage('settings')"),'mobile settings button must have an explicit route');
assert.ok(app.includes("$('solMobileAlmanac').onclick=()=>{window.location.href='today.html'}"),'mobile almanac button must open the existing calendar instrument');
for(const id of ['solTodayConclusion','solTodayAction','solTodayTime','solTodayCaution'])assert.ok(app.includes(`id="${id}"`),`${id} must be visible in the SOL today summary`);
assert.ok(app.indexOf('class="sol-today-summary"')<app.indexOf('class="dashboard"'),'the four-item summary must appear before the detailed calendar instrument');
assert.ok(app.includes('function solTodaySummary'),'today summary must be derived from the selected date');
for(const [page,target] of [['personal','personalForm'],['qimen','qm-panel-purpose'],['compat','compatForm'],['mundane','mundaneGenerate']]){
  assert.ok(app.includes(`data-sol-reading-page="${page}" data-sol-reading-target="${target}"`),`${page} card must point to its existing destination`);
  assert.ok(app.includes(`id="${target}"`)||app.includes(`id='${target}'`),`${page} destination must exist`);
}
const readingChoiceHandler=app.slice(app.indexOf('function koyomiBindReadingChoices'),app.indexOf('function koyomiBindMobileNavigation'));
assert.ok(readingChoiceHandler.indexOf('setPage(page)')<readingChoiceHandler.indexOf('requestAnimationFrame'),'reading cards must route before scrolling');
assert.ok(app.includes("if(page==='qimen')qmdjSetPanel('purpose')"),'Qimen card must reveal its purpose panel before scrolling');
assert.ok(!today.includes('今日の今日の暦機構'),'today navigation label must not be duplicated');
assert.ok(today.includes('<a href="app.html#settings"><b>⚙</b>設定</a>'),'settings navigation must use a distinct icon and real route');
assert.ok(today.includes('.bottomnav a{font-size:11px;min-height:48px}'),'today mobile navigation text must remain readable');
assert.ok(today.includes('<h1>今日の暦</h1>'),'today page must use the concise title');
assert.ok(today.includes('id="reloadBtn"'),'today page must expose a reload action');
assert.ok(today.includes("$('#reloadBtn').onclick=()=>window.location.reload()"),'reload action must refresh the page');
assert.ok(today.includes('syncCalendarDate(new Date());renderText()'),'today page must replace its sample date at startup');
assert.ok(today.includes('function localDateIso'),'today date must use local calendar components rather than UTC slicing');
assert.ok(today.includes('id="labyrinthWorks"'),'calendar clock must include the labyrinth gear layer');
for(const route of ['calendar','timeline','compat','ledger','settings'])assert.ok(today.includes(`href="app.html#${route}"`),`${route} must have a real bottom navigation route`);
assert.ok(!today.includes("$$('.bottomnav button')"),'today navigation must not use placeholder drawer handlers');

console.log('Mobile regression checks passed');
