import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const context={};for(const file of ['persona-policy.js','conversation-adapter.js'])vm.runInNewContext(await readFile(`src/persona/${file}`,'utf8'),context);const policy=context.KOYOMI_PERSONA_POLICY,adapter=context.KOYOMI_PERSONA_ADAPTER;
assert.equal(policy.plan({domain:'relationship',score:60}).mode,'empathetic');assert.equal(policy.plan({domain:'money',score:60}).mode,'grounded');assert.equal(policy.plan({domain:'health',score:60}).mode,'restorative');assert.equal(policy.plan({score:80}).mode,'decisive');assert.equal(policy.plan({score:55}).mode,'measured');assert.equal(policy.plan({score:80,contradiction:true}).mode,'reconcile');assert.equal(policy.plan({score:80,risk:90}).mode,'safety','safety must override every stylistic mode');
const safety=adapter.build({system:'相性鑑定',score:30,risk:95,evidence:['脅しあり'],domain:'relationship'});assert.equal(safety.personaMode,'safety');assert.equal(safety.aside,'');assert.doesNotMatch([safety.opening,safety.address,safety.bridge,safety.closing].join(' '),/あら|アンタ|景気|ときめき/);assert.match(safety.closing,/安全|危険|支援/);
const modes=new Set(),openings=new Set(),texts=[];for(let i=0;i<90;i++){const input={system:'総合鑑定',score:25+(i*19)%71,domain:['overall','work','money','relationship','health'][i%5],state:['forward','test','protect'][i%3],contradiction:i%11===0,risk:i%29===0?90:10,evidence:[`根拠${i%13}`],variant:i},layer=adapter.build(input),text=[layer.opening,layer.address,layer.bridge,layer.aside,layer.closing].filter(Boolean).join(' ');modes.add(layer.personaMode);openings.add(layer.opening);texts.push(text);assert.ok(layer.opening&&layer.bridge&&layer.closing);assert.ok(!/(アンタ[、。 ]*){2}/.test(text))}
assert.ok(modes.size>=7,`all conversation modes should appear: ${[...modes]}`);assert.ok(openings.size>=20,`openings need contextual variety: ${openings.size}`);assert.ok(texts.filter(text=>text.includes('アンタ')).length<=18,'direct address must not become a daily verbal tic');
const [app,worker]=await Promise.all([readFile('app.html','utf8'),readFile('service-worker.js','utf8')]);assert.ok(app.includes('src/persona/persona-policy.js'));assert.ok(worker.includes('./src/persona/persona-policy.js'));assert.ok(app.includes('judgment=window.KOYOMI_ACTIVE_JUDGMENT'));assert.ok(app.includes('contradiction:input.contradiction??judgment?.contradiction'));
console.log('Persona policy quality passed: 90 simulations');
