import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
const source=await readFile('src/persona/conversation-adapter.js','utf8'),context={};vm.runInNewContext(source,context);const adapter=context.KOYOMI_PERSONA_ADAPTER;
const base='【結論】\n慎重に進む。\n\n【何が起こりそうか】\n変化あり。\n\n【避ける行動】\n急がない。\n\n【最後の一言】\n元の締め。';
const normal=adapter.apply(base,{system:'総合鑑定',question:'転職するか迷っています',score:62,mode:'sister',reasons:['追い風は四柱推命・宿曜']});
assert.equal(normal.persona.focus,'追い風は四柱推命・宿曜');assert.ok(normal.text.includes('姐さんのひと言'));assert.ok(normal.text.includes('「追い風は四柱推命・宿曜」'));assert.equal(adapter.apply(base,{system:'総合鑑定',question:'別の相談文',score:62,mode:'sister',reasons:['追い風は四柱推命・宿曜']}).text,normal.text,'free-form consultation text must not affect the reading');
const different=adapter.apply(base,{system:'総合鑑定',score:78,mode:'sister',reasons:['警戒はタロット']});assert.notEqual(different.persona.opening,normal.persona.opening);
const danger=adapter.apply(base,{system:'相性鑑定',question:'相手に脅されて怖い',score:30,mode:'zubat',risk:95});assert.equal(danger.persona.serious,true);assert.equal(danger.persona.aside,'');assert.ok(!danger.text.includes('姐さんのひと言'));assert.match(danger.persona.closing,/安全|危険|第三者/);
for(const key of ['warm','bright','firm','bridge','aside','close'])assert.ok(adapter.BANK[key].length>=6);
const individual=adapter.applyDivination('【相談とケルト十字】\n相談「転職の面接が不安」を、カードで読みます。\n\n【相談への回答】\n条件を確認してください。慎重な判断が必要です。\n\n【判定の確度】\nこの計算は入力値を使います。',{system:'タロット',question:'転職の面接が不安',score:58,mode:'sister',evidence:['最終結果 正位置','障害 逆位置'],action:'面接条件を一つ確認する',variant:3});
assert.ok(individual.text.startsWith('【タロットを姐さんが読むわ】'));
assert.ok(individual.text.includes('条件を確認してちょうだい。'));
assert.ok(individual.text.includes('最終結果 正位置／障害 逆位置'));
assert.ok(individual.text.includes('最初の一手は「面接条件を一つ確認する」'));
assert.ok(individual.text.includes('【判定の確度】\nこの計算は入力値を使います。'),'technical evidence must retain neutral wording');
assert.ok(individual.text.includes('【姐さんの締め】'));
assert.ok(!individual.text.includes('転職の面接が不安'));
assert.ok(individual.text.includes('【ケルト十字の鑑定結果】'));
assert.ok(individual.text.includes('【鑑定結果からの結論】'));
console.log('Persona conversation adapter passed');
