import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
const source=await readFile('src/persona/conversation-adapter.js','utf8'),context={};vm.runInNewContext(await readFile('src/persona/sister-renderer.js','utf8'),context);vm.runInNewContext(await readFile('src/persona/reading-structure-planner.js','utf8'),context);vm.runInNewContext(await readFile('src/persona/persona-policy.js','utf8'),context);vm.runInNewContext(source,context);const adapter=context.KOYOMI_PERSONA_ADAPTER;
const base='【結論】\n慎重に進む。\n\n【何が起こりそうか】\n変化あり。\n\n【避ける行動】\n急がない。\n\n【最後の一言】\n元の締め。';
const normal=adapter.apply(base,{system:'総合鑑定',question:'転職するか迷っています',score:62,mode:'sister',reasons:['追い風は四柱推命・宿曜']});
assert.equal(normal.persona.focus,'追い風は四柱推命・宿曜');assert.ok(normal.text.includes('姐さんのひと言'));assert.ok(normal.text.includes('「追い風は四柱推命・宿曜」'));assert.equal(adapter.apply(base,{system:'総合鑑定',question:'別の相談文',score:62,mode:'sister',reasons:['追い風は四柱推命・宿曜']}).text,normal.text,'free-form consultation text must not affect the reading');
assert.ok(!normal.text.includes('を軸に'),'mechanical axis phrasing must not appear in readings');
assert.ok(adapter.BANK.address.length>=6);
const different=adapter.apply(base,{system:'総合鑑定',score:78,mode:'sister',reasons:['警戒はタロット']});assert.notEqual(different.persona.opening,normal.persona.opening);
const danger=adapter.apply(base,{system:'相性鑑定',question:'相手に脅されて怖い',score:30,mode:'zubat',risk:95});assert.equal(danger.persona.serious,true);assert.equal(danger.persona.aside,'');assert.ok(!danger.text.includes('姐さんのひと言'));assert.match(danger.persona.closing,/安全|危険|第三者/);
for(const key of ['warm','bright','firm','bridge','aside','close'])assert.ok(adapter.BANK[key].length>=6);
const individual=adapter.applyDivination('【相談とケルト十字】\n相談「転職の面接が不安」を、カードで読みます。\n\n【相談への回答】\n条件を確認してください。慎重な判断が必要です。\n\n【判定の確度】\nこの計算は入力値を使います。',{system:'タロット',question:'転職の面接が不安',score:58,mode:'sister',evidence:['最終結果 正位置','障害 逆位置'],action:'面接条件を一つ確認する',variant:3});
assert.ok(individual.text.startsWith('【タロットを姐さんが読むわ】'));
assert.ok(individual.text.includes('【詳しい鑑定資料】'));
assert.ok(individual.text.includes('最終結果 正位置／障害 逆位置'));
assert.ok(individual.text.includes('面接条件を一つ確認する'));
assert.ok(individual.text.includes('【判定の確度】\nこの計算は入力値を使います。'),'technical evidence must retain neutral wording');
assert.ok(individual.text.includes('【最後に姐さんから】'));
assert.ok(!individual.text.includes('転職の面接が不安'));
assert.ok(individual.text.includes('【ケルト十字の鑑定結果】'));
assert.ok(individual.text.includes('【鑑定結果からの結論】'));
assert.ok(individual.structure?.structureId,'standard readings must receive a deterministic structure plan');
assert.ok(!['現実に出やすい形','まず、これをおやりなさい','ここで止まりなさい','あとで確かめること'].every(heading=>individual.text.includes(`【${heading}】`)),'all fixed headings must not be forced into every reading');
assert.ok(individual.text.includes('相手の反応・障害の再発・結果へ向かう変化'));
assert.equal(individual.scenario.review,'7日');
const defensive=adapter.concreteScenario({system:'大運・暦',score:32,evidence:['大運 低調'],action:'契約を保留する'});assert.equal(defensive.state,'防御');assert.match(defensive.scene,/判断を急がず|準備/);assert.doesNotMatch(defensive.scene,/返信の遅れ/);assert.equal(defensive.review,'30日');
const allSystems=['四柱推命','宿曜','九星気学','西洋占星術','タロット','ルーン','姓名判断','数秘術','カバラ','六星周期','大運・暦'];for(const system of allSystems){assert.ok(adapter.DOMAINS[system],`${system} needs a concrete domain model`);assert.ok(adapter.PLAYBOOKS[system],`${system} needs an actionable playbook`);const scenario=adapter.concreteScenario({system,score:55});assert.ok(scenario.action.length>12 && /確認|整理|記録|見直|分け|考え|決め|比べ/.test(scenario.action));assert.doesNotMatch(scenario.action,/小さく|\d+分|一件だけ|一つだけ/);assert.ok(scenario.go.length>12)}
assert.match(defensive.stop,/準備や合意/);
assert.doesNotMatch(defensive.stop,/支払い|体調/);
assert.match(adapter.concreteScenario({system:"大運・暦",domain:"health"}).stop,/悪化|医療機関/);
assert.doesNotMatch(defensive.stop,/二時間/);
assert.equal(adapter.concreteScenario({score:0}).state,'防御');
console.log('Persona conversation adapter passed');
