import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const files=['western-core-v1.js','western-transits-v1.js','western-synastry-v1.js','western-solar-return-v1.js','western-progressions-v1.js','western-dignities-v1.js','western-points-v1.js','western-patterns-v1.js','western-composite-v1.js','western-professional-v1.js','western-reading-v1.js','western-chart-wheel-v1.js','western-forecast-v1.js','western-solar-arc-v1.js','western-davison-v1.js','western-fixed-stars-v1.js','western-suite-loader.js'];
const context={console,Date,setTimeout,document:{readyState:'loading',addEventListener(){},getElementById(){return null}}};context.globalThis=context;
for(const file of files)vm.runInNewContext(await readFile(`src/astrology/${file}`,'utf8'),context,{filename:file});
const day=86400000,birth=new Date('1990-01-01T00:00:00Z'),target=new Date('2020-01-01T00:00:00Z');
const eph=date=>{const d=(new Date(date)-birth)/day;return{太陽:(280+d*.98564736)%360,月:(100+d*13.176)%360,水星:(290+d*1.1)%360,金星:(330+d*.8)%360,火星:(20+d*.5)%360,木星:(100+d*.08)%360,土星:(270+d*.033)%360}};
const result=context.WesternAstrologySuite.buildResult({placements:{太陽:280,月:100,水星:290,金星:330,火星:20,木星:100,土星:270},angles:{asc:10,mc:280},birthMoment:birth,targetDate:target,year:2020,ephemeris:eph,partnerPlacements:{太陽:100,月:280,金星:20,火星:330},points:{birthMoment:birth},birthTimeKnown:true});
assert.equal(result.dignities.placements.火星.kind,'domicile');
assert.ok(result.points.items.some(x=>x.name==='ドラゴンヘッド'));
assert.ok(result.points.items.some(x=>x.name==='Part of Fortune'));
assert.equal(result.progressions.available,true);
assert.ok(Math.abs(result.progressions.progressedDays-30)<.1);
assert.equal(result.solarReturn.available,true);
assert.equal(result.synastry.available,true);
assert.ok(result.transits.items.length>0);
assert.equal(result.professional.warnings.length,0);
console.log('Western professional calculations passed');
