import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const files=['western-core-v1.js','western-transits-v1.js','western-synastry-v1.js','western-solar-return-v1.js','western-progressions-v1.js','western-dignities-v1.js','western-points-v1.js','western-patterns-v1.js','western-composite-v1.js','western-professional-v1.js','western-reading-v1.js','western-chart-wheel-v1.js','western-forecast-v1.js','western-solar-arc-v1.js','western-davison-v1.js','western-fixed-stars-v1.js','western-suite-loader.js'];
const context={console,Date,setTimeout,document:{readyState:'loading',addEventListener(){},getElementById(){return null}}};context.globalThis=context;
for(const file of files)vm.runInNewContext(await readFile(`src/astrology/${file}`,'utf8'),context,{filename:file});
const epoch=new Date('1990-01-01T00:00:00Z'),day=86400000,eph=date=>{const d=(new Date(date)-epoch)/day;return{太陽:(280+d*.9856)%360,月:(100+d*13.176)%360,水星:(290+d*1.1)%360,金星:(330+d*.8)%360,火星:(20+d*.5)%360,木星:(100+d*.08)%360,土星:(270+d*.033)%360}};
const result=context.WesternAstrologySuite.buildResult({placements:eph(epoch),angles:{asc:10,mc:280},cusps:Array.from({length:12},(_,i)=>10+i*30),birthMoment:epoch,partnerMoment:new Date('1992-01-01T00:00:00Z'),partnerTimeKnown:true,targetDate:new Date('2026-01-01T00:00:00Z'),ephemeris:eph,birthTimeKnown:true,partnerPlacements:eph(new Date('1992-01-01T00:00:00Z'))});
assert.equal(result.schemaVersion,'western-120-v1');
assert.equal(result.calculationMeta.offlineLevel,'B');
assert.ok(result.chartWheel.svg.startsWith('<svg'));
assert.equal(result.forecast.available,true);
assert.equal(result.solarArc.available,true);
assert.equal(result.davison.available,true);
assert.equal(result.fixedStars.available,true);
assert.ok(!('reading' in result.consensusTags));
console.log('Western astrology 120% features passed');
