import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createWorldContext, consensusOf, createSpatialGrid, EqualAreaBandGrid, H3SpatialGrid, MundaneEarthquakeAdapter, MUNDANE_EARTHQUAKE_VERSION, normalizeMundanePositions, WorldEvaluationCache, relateEventToCell, validateWorldEvent } from '../src/world/index.js';
import { createWorldGraticule } from '../src/world/world-graticule.js';

const context=createWorldContext({datetimeUtc:'2026-08-20T00:00:00+09:00',latitude:35.68,longitude:139.77,themeId:'earthquake',mode:'forecast'});
assert.equal(context.datetimeUtc,'2026-08-19T15:00:00.000Z');
assert.throws(()=>createWorldContext({datetimeUtc:'bad',themeId:'earthquake',mode:'forecast'}),/valid date/);
assert.throws(()=>createWorldContext({datetimeUtc:new Date(),latitude:91,themeId:'earthquake',mode:'forecast'}),/latitude/);

const grid=createSpatialGrid();assert.ok(grid instanceof H3SpatialGrid);assert.equal(grid.systemId,'h3');assert.equal(grid.version,'4.5.0');
for(const [lat,lon] of [[0,0],[35.6812,139.7671],[80,20],[-80,-20],[0,179.999],[0,-180],[89.9,0],[-89.9,0]]){
  const id=grid.cellForLatLng(lat,lon,3);assert.equal(id,grid.cellForLatLng(lat,lon,3));assert.equal(grid.resolution(id),3);
  const boundary=grid.boundary(id);assert.ok(boundary.length>=6);assert.ok(boundary.flat().every(Number.isFinite));assert.ok(grid.cellAreaKm2(id)>0);
  assert.equal(grid.parent(id,2),grid.parent(id,2));assert.ok(grid.children(grid.parent(id,2),3).includes(id));assert.ok(grid.neighbors(id,1).includes(id));
}
assert.notEqual(grid.cellForLatLng(0,179.9,5),grid.cellForLatLng(0,-179.9,5));
assert.deepEqual([grid.resolutionForZoom(1),grid.resolutionForZoom(3),grid.resolutionForZoom(5),grid.resolutionForZoom(7),grid.resolutionForZoom(10)],[1,2,3,4,5]);
const worldCells=grid.viewportCells({south:-89,north:89,west:-180,east:180},0,500);assert.ok(worldCells.length>=100&&worldCells.length<=500);assert.ok(worldCells.some(id=>grid.isPentagon(id)),'world cells must include H3 pentagons');
const datelineCells=grid.viewportCells({south:-10,north:10,west:170,east:-170},2,500);assert.ok(datelineCells.some(id=>grid.center(id).longitude>160));assert.ok(datelineCells.some(id=>grid.center(id).longitude< -160));
const datelineId=grid.cellForLatLng(0,179.9,3),datelineFeature=grid.geoJson([datelineId]).features[0];assert.equal(datelineFeature.geometry.type,'MultiPolygon');for(const polygon of datelineFeature.geometry.coordinates){const ring=polygon[0];assert.deepEqual(ring[0],ring.at(-1),'dateline polygon rings must be closed');for(let index=1;index<ring.length;index++)assert.ok(Math.abs(ring[index][0]-ring[index-1][0])<=180,'dateline polygon must not draw across the globe')}
const polarFeature=grid.geoJson(['8001fffffffffff']).features[0];assert.equal(polarFeature.geometry.type,'MultiPolygon');for(const polygon of polarFeature.geometry.coordinates){const ring=polygon[0];assert.deepEqual(ring[0],ring.at(-1),'polar polygon rings must be closed');for(let index=1;index<ring.length;index++)assert.ok(Math.abs(ring[index][0]-ring[index-1][0])<=180,'polar polygon must not draw across the globe')}
const tokyoFeature=grid.geoJson([grid.cellForLatLng(35.6812,139.7671,3)]).features[0];assert.equal(tokyoFeature.geometry.type,'Polygon');assert.deepEqual(tokyoFeature.geometry.coordinates[0][0],tokyoFeature.geometry.coordinates[0].at(-1),'ordinary H3 polygon rings must be closed');

const fallback=new EqualAreaBandGrid();assert.equal(fallback.systemId,'koyomi-equal-area-band');assert.match(fallback.cellForLatLng(35,139,2),/^kea1:/);

const ephemeris={id:'world-test',planetLongitudes(){return{Sun:0,Moon:180,Mars:0,Saturn:90,Uranus:180,Pluto:270}}},adapter=new MundaneEarthquakeAdapter(ephemeris),cellId=grid.cellForLatLng(context.latitude,context.longitude,2),resultContext={...context,spatialCellId:cellId,gridSystemId:grid.systemId,gridVersion:grid.version,resolution:2};
const result=adapter.evaluate(resultContext);assert.equal(result.version,MUNDANE_EARTHQUAKE_VERSION);assert.equal(result.gridSystemId,'h3');assert.equal(result.gridVersion,'4.5.0');assert.equal(result.resolution,2);assert.equal(result.contributors.length,3);assert.equal(result.confidence,'experimental');
assert.deepEqual(consensusOf([result],70),{matched:1,total:1,threshold:70});assert.equal(adapter.evaluate(resultContext).score,result.score);
assert.equal(result.metadata.calculationQuality,'complete');assert.equal(result.consensus.available,3);assert.ok(result.contributors.every(item=>['active','inactive'].includes(item.status)));assert.ok(result.contributors.some(item=>item.details.length));
assert.deepEqual(normalizeMundanePositions({太陽:360,月:-1,火星:0,土星:90,天王星:180,冥王星:270}),{Sun:0,Moon:359,Mars:0,Saturn:90,Uranus:180,Pluto:270});
const japaneseEphemeris={id:'fallback-test',precision:'fallback',planetLongitudes(){return{太陽:0,月:180,火星:0,土星:90,天王星:180,冥王星:270}}},japaneseResult=new MundaneEarthquakeAdapter(japaneseEphemeris).evaluate(resultContext);assert.equal(japaneseResult.score,result.score,'Japanese and English body names must produce the same public score');assert.deepEqual(japaneseResult.contributors.map(item=>item.status),result.contributors.map(item=>item.status));
const incompleteResult=new MundaneEarthquakeAdapter({id:'incomplete',planetLongitudes(){return{太陽:0,月:180}}}).evaluate(resultContext);assert.equal(incompleteResult.metadata.calculationQuality,'partial');assert.equal(incompleteResult.consensus.available,1);assert.equal(incompleteResult.contributors[0].status,'unavailable');assert.equal(incompleteResult.contributors[1].status,'unavailable');assert.equal(incompleteResult.contributors[2].status,'active');assert.match(incompleteResult.contributors[0].reason,/不足/);
const unavailableResult=new MundaneEarthquakeAdapter({id:'empty',planetLongitudes(){return{}}}).evaluate(resultContext);assert.equal(unavailableResult.metadata.calculationQuality,'unavailable');assert.equal(unavailableResult.consensus.available,0);assert.ok(unavailableResult.contributors.every(item=>item.status==='unavailable'));
for(const separation of [5.99,6,6.01]){const boundaryResult=new MundaneEarthquakeAdapter({planetLongitudes(){return{Sun:30,Moon:90,Mars:0,Saturn:90+separation,Uranus:230,Pluto:310}}}).evaluate(resultContext),hard=boundaryResult.contributors[0];assert.equal(hard.active,separation<=6,`hard aspect orb ${separation} must respect the inclusive 6 degree boundary`)}
const cache=new WorldEvaluationCache(2);assert.strictEqual(cache.evaluate(resultContext,adapter),cache.evaluate(resultContext,adapter));assert.equal(cache.size,1);cache.clear();assert.equal(cache.size,0);

const eventData=JSON.parse(await readFile(new URL('../data/world/validation-events.json',import.meta.url),'utf8'));assert.equal(eventData.schemaId,'koyomi-world-validation-events-v1');assert.ok(eventData.events.length>=3);
for(const event of eventData.events){validateWorldEvent(event);const eventCell=grid.cellForLatLng(event.latitude,event.longitude,3),relation=relateEventToCell(event,eventCell,grid);assert.equal(relation.sameCell,true);assert.equal(relation.ring,0);assert.ok(relation.centerDistanceKm>=0)}
assert.throws(()=>validateWorldEvent({}),/identity/);

const graticule=createWorldGraticule();assert.equal(graticule.type,'FeatureCollection');assert.ok(graticule.features.length>=17);assert.ok(graticule.features.some(feature=>feature.properties.axis==='equator'));assert.ok(graticule.features.some(feature=>feature.properties.axis==='prime-meridian'));assert.ok(graticule.features.every(feature=>feature.geometry.coordinates.flat().every(Number.isFinite)));

const worker=await readFile(new URL('../service-worker.js',import.meta.url),'utf8');for(const asset of ['vendor/h3-js/4.5.0/h3-js.es.js','vendor/h3-js/4.5.0/LICENSE','data/world/validation-events.json'])assert.ok(worker.includes(asset),`${asset} must be cached offline`);
for(const asset of ['vendor/maplibre-gl/5.24.0/maplibre-gl.js','vendor/maplibre-gl/5.24.0/maplibre-gl.css','data/map/natural-earth-50m-countries.geojson','data/map/natural-earth-50m-lakes.geojson','src/world/world-graticule.js'])assert.ok(worker.includes(asset),`${asset} must be in the map core cache`);
for(const token of ['MAP_CORE_CACHE','MAP_REGION_CACHE','Promise.allSettled','cacheFirstMapCore'])assert.ok(worker.includes(token),`${token} must protect offline map caching`);
const mapUi=await readFile(new URL('../src/world/world-map-ui.js',import.meta.url),'utf8');assert.ok(mapUi.includes('MAX_VISIBLE_CELLS=1000'));assert.ok(mapUi.includes('while(ids.length>=MAX_VISIBLE_CELLS'));assert.ok(mapUi.includes("map.on('moveend',scheduleUpdate)"));assert.ok(mapUi.includes('setTimeout(update,180)'));assert.ok(mapUi.includes("MAPLIBRE_JS='./vendor/maplibre-gl/5.24.0/maplibre-gl.js'"));for(const token of ["map.setProjection({type:'globe'})","map.getProjection()",'globeZoomFor','worldGlobeReset','地球全体'])assert.ok(mapUi.includes(token),`${token} must enforce the globe presentation`);assert.ok(!/unpkg|demotiles\.maplibre/.test(mapUi),'world map must not depend on map CDNs');
for(const token of ['role="switch"','earthquakePreviewHorizon','previewBand'])assert.ok(mapUi.includes(token),`${token} must support the release-gated earthquake layer`);
const offlineStyle=await readFile(new URL('../src/world/offline-map-style.js',import.meta.url),'utf8');assert.ok(offlineStyle.includes('Natural Earth 1:50m'));for(const token of ["projection:{type:'globe'}","graticule:{type:'geojson'",'land-outline-halo'])assert.ok(offlineStyle.includes(token),`${token} must make the offline globe visible`);assert.ok(!/https?:\/\//.test(offlineStyle));assert.ok(!/glyphs|sprite/.test(offlineStyle));
const countries=JSON.parse(await readFile(new URL('../data/map/natural-earth-50m-countries.geojson',import.meta.url),'utf8'));assert.equal(countries.type,'FeatureCollection');assert.ok(countries.features.length>200);const japan=countries.features.find(feature=>feature.properties.ADMIN==='Japan');assert.ok(japan);assert.equal(japan.geometry.type,'MultiPolygon');assert.ok(japan.geometry.coordinates.length>=20,'offline base map must retain Japanese islands');assert.equal(countries.koyomiSource.license,'Public Domain');
const lakes=JSON.parse(await readFile(new URL('../data/map/natural-earth-50m-lakes.geojson',import.meta.url),'utf8'));assert.equal(lakes.type,'FeatureCollection');assert.ok(lakes.features.length>100);
console.log('World forecast H3 and validation foundation passed');
