import { VOLCANO_LAYER_DEFAULTS } from './config.js';
import { evaluateVolcanoReleaseGate } from './release-gate.js';
import { volcanoPublicView } from './display-policy.js';
import { distanceKm } from './seismic-coupling.js';
import { evaluateHeatTransfer } from './heat-transfer.js';
import { evaluateVolcanoSeismicCoupling } from './seismic-coupling.js';
import { normalizeOfficialAlert, observationRing } from './alert-level.js';
import { localizedVolcanoName } from './localization.js';
import { normalizeObservationIds } from './observation-compat.js';

const SOURCE_ID='world-volcanoes',LAYER_IDS=['world-volcano-clusters','world-volcano-cluster-count','world-volcano-points'],EARTHQUAKE_LAYERS=['world-grid-fill','world-grid-quiescence','world-grid-geomagnetic','world-grid-line','forecast-outcome-clusters','forecast-outcome-cluster-count','forecast-outcome-dots'];
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const emptySignal=Object.freeze({status:'data-unavailable',classification:null,reason:'観測データはまだ接続されていません'});

export async function loadVolcanoCatalog(){const response=await fetch('./data/world/volcano-catalog-v2.json');if(!response.ok)throw new Error('volcano catalog unavailable');const data=await response.json();if(data.schemaId!=='koyomi-volcano-catalog-v2'||data.officialStatusIncluded!==false||!Array.isArray(data.volcanoes)||data.volcanoes.length<1000||!/^[a-f0-9]{64}$/i.test(data.sha256||''))throw new Error('invalid volcano catalog');return data;}
export async function loadVolcanoObservations(catalog=null){const response=await fetch('./data/world/volcano-observations-v1.json');if(!response.ok)throw new Error('volcano observations unavailable');const data=await response.json();if(data.schemaId!=='koyomi-volcano-observations-v1'||!data.thermalByVolcano||!data.seismicByVolcano)throw new Error('invalid volcano observations');return catalog?normalizeObservationIds(data,catalog):data;}
export async function loadVolcanoOfficialAlerts(){const response=await fetch('./data/world/volcano-official-alerts-v1.json');if(!response.ok)throw new Error('volcano official alerts unavailable');const data=await response.json();if(data.schemaId!=='koyomi-volcano-official-alerts-v1'||!data.alertsByVolcano)throw new Error('invalid volcano official alerts');return data;}

const heatBandFor=(thermal,mode)=>{if(!thermal||['unconfigured','data-unavailable'].includes(thermal.status))return 0;if(thermal.status==='no-detection')return 1;if(mode==='frp'){const value=Number(thermal.totalFrpMw)||0;return value>=100?4:value>=10?3:2}return thermal.multiSensorConfirmed?4:(Number(thermal.detectionCount)||0)>=3?3:2};
const heatColorFor=band=>['#7a858c','#4b91b5','#e2bd49','#e57a2c','#a63d72'][band]||'#7a858c';
export function volcanoGeoJson(catalog,observations,heatMode='confirmation',officialAlerts=null,{asOf=new Date()}={}){return{type:'FeatureCollection',features:catalog.volcanoes.map(volcano=>{const thermal=observations?.thermalByVolcano?.[volcano.id],seismic=observations?.seismicByVolcano?.[volcano.id],heatBand=heatBandFor(thermal,heatMode),alert=normalizeOfficialAlert(officialAlerts?.alertsByVolcano?.[volcano.id],{asOf}),ring=observationRing(thermal,seismic),localized=localizedVolcanoName(volcano);return{type:'Feature',id:volcano.id,properties:{id:volcano.id,name:localized.nameJa,nameEn:localized.nameEn,nameJaStatus:localized.status,region:volcano.region,country:volcano.country||volcano.region,officialStatus:alert.status,alertBand:alert.band,alertColor:alert.color,alertSymbol:alert.symbol,alertLabel:alert.labelJa,observationRingBand:ring.band,observationRingColor:ring.color,observationRingLabel:ring.label,heatBand,heatColor:heatColorFor(heatBand),multiSensorConfirmed:thermal?.multiSensorConfirmed===true,totalFrpMw:Number(thermal?.totalFrpMw)||0,detectionCount:Number(thermal?.detectionCount)||0},geometry:{type:'Point',coordinates:[volcano.longitude,volcano.latitude]}}})}}

export function createVolcanoMapController({page,map,sheet,catalog,observations,officialAlerts,getAsOf=()=>new Date()}){
  let active=false,state={...VOLCANO_LAYER_DEFAULTS};
  const gate=evaluateVolcanoReleaseGate({futureLeakageBlocked:true});
  const control=page.querySelector('#volcanoLayerControl');
  const heatModeSelect=control.querySelector('#volcanoHeatMode');
  const setVisibility=visible=>LAYER_IDS.forEach(id=>map.getLayer(id)&&map.setLayoutProperty(id,'visibility',visible?'visible':'none'));
  const signalFor=volcano=>{const thermalData=observations?.thermalByVolcano?.[volcano.id],seismicData=observations?.seismicByVolcano?.[volcano.id],asOf=getAsOf(),thermal=thermalData?.status==='available'?evaluateHeatTransfer((thermalData.detections||[]).map(item=>({timeUtc:item.timeUtc,value:item.frpMw,weatherQuality:item.confidence==='l'?'poor':'good'})),{asOf}):thermalData?.status==='no-detection'?Object.freeze({status:'no-detection',classification:null,reason:'衛星熱源の検出はありませんが、雲や観測間隔による未検出を含みます'}):thermalData?.status==='stale-data'?Object.freeze({status:'stale-data',classification:null,reason:'前回成功時の熱観測です。現在の状態を示すものではありません'}):emptySignal,seismic=seismicData?.status==='available'?evaluateVolcanoSeismicCoupling(volcano,seismicData.events,{asOf,maxAgeHours:24}):emptySignal;return{thermal,seismic,thermalData,seismicData}};
  const statusText=value=>({'available':'観測あり','no-detection':'検出なし（安全判定ではありません）','data-unavailable':'データ未取得','stale-data':'更新停止中','partial-data':'観測条件不良'}[value]||'比較保留');
  const renderVolcano=volcano=>{const signals=signalFor(volcano),localized=localizedVolcanoName(volcano),nameNote=localized.status==='unverified-original'?'日本語名未確認':localized.nameEn,alert=normalizeOfficialAlert(officialAlerts?.alertsByVolcano?.[volcano.id],{asOf:getAsOf()}),ring=observationRing(signals.thermalData,signals.seismicData),view=volcanoPublicView({volcano:{...volcano,name:localized.nameJa},official:alert.status==='available'?alert:null,thermal:signals.thermal,seismic:signals.seismic,gate}),updated=signals.thermalData?.lastSuccessfulObservationAt||signals.thermalData?.latestObservationUtc||observations?.generatedAt||null,updatedLabel=updated?new Date(updated).toISOString().slice(0,16).replace('T',' '):'未取得',officialLink=alert.sourceUrl||'https://www.data.jma.go.jp/vois/data/filing/volcano.html';sheet.innerHTML=`<section class="world-volcano-card"><header><div><small>公式情報・観測研究を分離表示</small><h3>${esc(view.name)}</h3><small>${esc(nameNote)}／GVP ${esc(volcano.gvpNumber)}</small></div><b class="world-volcano-alert-badge" style="--alert-color:${esc(alert.color)}">${esc(alert.symbol)} ${esc(alert.labelJa)}</b></header><p class="world-card-location">${volcano.latitude.toFixed(3)}°, ${volcano.longitude.toFixed(3)}°／${esc(volcano.region)}</p><div class="world-volcano-official" style="--alert-color:${esc(alert.color)}"><h4>最優先：公式状態</h4><strong>${esc(alert.symbol)} ${esc(alert.labelJa)}</strong><p>${esc(alert.reason)}${alert.status!=='available'?'。未取得は「安全」を意味しません。':''}</p><small>発表：${esc(alert.sourceAgency||'未取得')}／${esc(alert.issuedAt||'更新日時未取得')}</small><a href="${esc(officialLink)}" target="_blank" rel="noopener">公的機関の最新情報を確認</a></div><details ${state.observations?'open':''}><summary>観測変化：${esc(ring.label)}</summary><div class="world-volcano-observation-grid"><div><span>熱移送</span><b>${esc(statusText(signals.thermal.status))}</b><small>${esc(signals.thermal.reason||'比較保留')}</small></div><div><span>複数衛星一致</span><b>${signals.thermalData?.multiSensorConfirmed?'確認':'未確認'}</b><small>${signals.thermalData?.sensorCount??'—'}センサー</small></div><div><span>火山周辺地震</span><b>${esc(statusText(signals.seismic.status))}</b><small>${signals.seismic.count??signals.seismicData?.eventCount??'—'}件</small></div><div><span>最終成功観測</span><b>${esc(updatedLabel)}</b><small>${signals.thermalData?.stale?'古い観測・参考表示':observations?.freshness?.complete?'取得完了':'一部未取得'}</small></div></div><p>外周リングは観測変化です。危険度ではなく、公的警戒色を変更しません。</p></details><div class="world-volcano-research"><b>${esc(view.research.label)}</b><p>研究レイヤーは初期OFFです。将来情報の遮断、前向き検証、誤警報率・見逃し率の公開、熱・地震それぞれの除外試験を通るまで、噴火確率や時期を表示しません。</p></div><details ${state.mundane?'open':''}><summary>マンデン占術（独立表示）</summary><p>科学・観測モデルには一切加算しません。</p></details></section>`};
  const nearest=lngLat=>catalog.volcanoes.map(volcano=>({volcano,distance:distanceKm({latitude:lngLat.lat,longitude:lngLat.lng},volcano)})).sort((a,b)=>a.distance-b.distance)[0];
  if(!map.getSource(SOURCE_ID)){map.addSource(SOURCE_ID,{type:'geojson',data:volcanoGeoJson(catalog,observations,state.heatMode,officialAlerts,{asOf:getAsOf()}),cluster:true,clusterRadius:42,clusterMaxZoom:6,clusterProperties:{maxAlertBand:['max',['get','alertBand']],observationActiveCount:['+',['case',['>=',['get','observationRingBand'],1],1,0]]}});map.addLayer({id:'world-volcano-clusters',type:'circle',source:SOURCE_ID,filter:['has','point_count'],layout:{visibility:'none'},paint:{'circle-radius':['step',['get','point_count'],14,8,19,30,25],'circle-color':['match',['get','maxAlertBand'],4,'#c72f35',3,'#e27622',2,'#d5ad22',1,'#26845b','#707982'],'circle-stroke-color':'#fff1c7','circle-stroke-width':2}});map.addLayer({id:'world-volcano-cluster-count',type:'symbol',source:SOURCE_ID,filter:['has','point_count'],layout:{visibility:'none','text-field':['concat',['get','point_count_abbreviated'],' / 変化 ',['get','observationActiveCount']],'text-size':10},paint:{'text-color':'#fff'}});map.addLayer({id:'world-volcano-points',type:'circle',source:SOURCE_ID,filter:['!', ['has','point_count']],layout:{visibility:'none'},paint:{'circle-radius':['interpolate',['linear'],['zoom'],0,4,6,9],'circle-color':['get','alertColor'],'circle-stroke-color':['get','observationRingColor'],'circle-stroke-width':['case',['>=',['get','observationRingBand'],1],4,2]}})}
  map.on('click','world-volcano-points',event=>{if(active&&event.features?.[0]){const volcano=catalog.volcanoes.find(item=>item.id===event.features[0].properties.id);if(volcano)renderVolcano(volcano)}});
  map.on('click',event=>{if(!active||event.defaultPrevented)return;const item=nearest(event.lngLat);if(item?.distance<=150)renderVolcano(item.volcano)});
  control.querySelectorAll('input[data-volcano-layer]').forEach(input=>input.onchange=()=>{state={...state,[input.dataset.volcanoLayer]:input.checked};if(input.dataset.volcanoLayer==='research'&&!gate.released){input.checked=false;state.research=false;control.querySelector('#volcanoReleaseState').textContent='公開条件未達のためOFF'}if(input.dataset.volcanoLayer==='thermal')map.getSource(SOURCE_ID)?.setData(volcanoGeoJson(catalog,state.thermal?observations:null,state.heatMode,officialAlerts,{asOf:getAsOf()}))});
  if(heatModeSelect)heatModeSelect.onchange=()=>{state={...state,heatMode:heatModeSelect.value};map.getSource(SOURCE_ID)?.setData(volcanoGeoJson(catalog,observations,state.heatMode,officialAlerts,{asOf:getAsOf()}))};
  return Object.freeze({setActive(value){active=Boolean(value);control.hidden=!active;state.enabled=active;setVisibility(active);EARTHQUAKE_LAYERS.forEach(id=>map.getLayer(id)&&map.setLayoutProperty(id,'visibility',active?'none':'visible'));if(active)sheet.innerHTML='<b>火山を選択</b><p>地図上の火山点をタップすると、公式状態を最優先にした詳細を表示します。</p>';},get state(){return Object.freeze({...state})},gate});
}
