export const LEGACY_VOLCANO_ID_MAP=Object.freeze({
  'jma-aso':'gvp-282110','jma-sakurajima':'gvp-282080','jma-kirishima':'gvp-282090','jma-asama':'gvp-283110','jma-fuji':'gvp-283030','jma-ontake':'gvp-283040',
  'gvp-kilauea':'gvp-332010','gvp-etna':'gvp-211060','gvp-merapi':'gvp-263250','gvp-popocatepetl':'gvp-341090'
});
const unavailableThermal=()=>({status:'data-unavailable',detectionCount:null,sensorCount:null,multiSensorConfirmed:false,maximumBrightnessKelvin:null,totalFrpMw:null,latestObservationUtc:null,lastSuccessfulObservationAt:null,stale:true,detections:[]});
const unavailableSeismic=()=>({status:'data-unavailable',coverage:'global-M2.5-plus-context',eventCount:null,maximumMagnitude:null,latestObservationUtc:null,events:[]});
const migrateTable=(source,map)=>{const result={...source},migrated=[];for(const [legacyId,gvpId] of Object.entries(map)){if(!source?.[legacyId])continue;if(!result[gvpId])result[gvpId]=source[legacyId];delete result[legacyId];migrated.push({legacyId,gvpId})}return{result,migrated}};
export function normalizeObservationIds(data,catalog){const thermal=migrateTable(data?.thermalByVolcano||{},LEGACY_VOLCANO_ID_MAP),seismic=migrateTable(data?.seismicByVolcano||{},LEGACY_VOLCANO_ID_MAP),thermalByVolcano={},seismicByVolcano={};for(const volcano of catalog.volcanoes){thermalByVolcano[volcano.id]=thermal.result[volcano.id]||unavailableThermal();seismicByVolcano[volcano.id]=seismic.result[volcano.id]||unavailableSeismic()}const unresolved=[...Object.keys(thermal.result),...Object.keys(seismic.result)].filter(id=>!catalog.volcanoes.some(volcano=>volcano.id===id));return Object.freeze({...data,thermalByVolcano,seismicByVolcano,migration:Object.freeze({schemaId:'legacy-to-gvp-v1',migratedIds:[...new Map([...thermal.migrated,...seismic.migrated].map(item=>[item.legacyId,item])).values()],unresolvedIds:[...new Set(unresolved)]})})}
export function retainedThermal(previous,{generatedAt,failedSources=[]}={}){if(!previous||!['available','no-detection','stale-data'].includes(previous.status))return unavailableThermal();return{...previous,status:'stale-data',stale:true,retainedAfterProviderFailure:true,failedSources:[...failedSources],lastSuccessfulObservationAt:previous.lastSuccessfulObservationAt||previous.latestObservationUtc||generatedAt}}
