import { createSpatialGrid, MundaneEarthquakeAdapter, WorldEvaluationCache, relateEventToCell, validateWorldEvent } from './index.js';
import { createOfflineWorldStyle } from './offline-map-style.js';
import { calculateDatedPreview, createForecastLayerState, eventsAfterPreview } from './earthquake-forecast/index.js';

const MAPLIBRE_JS='./vendor/maplibre-gl/5.24.0/maplibre-gl.js';
const MAPLIBRE_CSS='./vendor/maplibre-gl/5.24.0/maplibre-gl.css';
const MAX_VISIBLE_CELLS=500;
const GLOBE_CENTER=[135,25];

const globeZoomFor=element=>element.clientWidth<=430?0:element.clientWidth<=760?0.45:0.85;

function loadMapLibre(){
  if(window.maplibregl)return Promise.resolve(window.maplibregl);
  if(!document.querySelector(`link[href="${MAPLIBRE_CSS}"]`)){const link=document.createElement('link');link.rel='stylesheet';link.href=MAPLIBRE_CSS;document.head.append(link)}
  return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=MAPLIBRE_JS;script.onload=()=>resolve(window.maplibregl);script.onerror=()=>reject(new Error('map library unavailable'));document.head.append(script)});
}

async function loadEvents(){
  const response=await fetch('./data/world/validation-events.json');if(!response.ok)throw new Error('validation events unavailable');
  const data=await response.json();return data.events.map(validateWorldEvent);
}

async function loadResearchPreview(){
  const response=await fetch('./data/world/earthquake-research-preview-v1.json');if(!response.ok)throw new Error('research preview unavailable');
  const data=await response.json();if(data.schemaId!=='koyomi-earthquake-research-preview-v1'||data.realHoldoutExecuted!==false||data.bandMethod!=='target-specific-all-horizon-fixed-quantiles-v1'||!Array.isArray(data.rows))throw new Error('invalid research preview');return data;
}

async function loadResearchCatalog(){
  const response=await fetch('./data/world/earthquake-research-catalog-v2.json');if(!response.ok)throw new Error('research catalog unavailable');
  const data=await response.json();if(data.schemaId!=='koyomi-earthquake-research-catalog-v2'||data.freshness?.complete!==true||!data.eventsByCell||!Number.isFinite(data.latestTimeUtcMs))throw new Error('invalid research catalog');return data;
}

const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const level=score=>score>=80?'高反応':score>=70?'やや高い':score>=40?'中程度':'低い';
const color=score=>score>=80?'#b42318':score>=70?'#e46f19':score>=40?'#d9a514':'#1e7f68';
const localInputValue=date=>{const d=new Date(date),offset=d.getTimezoneOffset()*60000;return new Date(d-offset).toISOString().slice(0,16)};
const contributorState=item=>item.status==='unavailable'?'計算不能':item.active?'高反応':'低反応';
const motionLabel=value=>({applying:'接近中',separating:'離反中',stationary:'変化僅少',unknown:'判定不能'}[value]||'判定不能');
const calculationQualityLabel=value=>({complete:'完全',partial:'一部不足',unavailable:'計算不能'}[value]||'未指定');
const ephemerisLabel=metadata=>metadata.ephemerisId==='astronomy-engine'?'Astronomy Engine':metadata.ephemerisPrecision==='fallback'?'内蔵近似計算':'天文計算エンジン';
const precisionLabel=value=>({high:'高精度',fallback:'近似',unspecified:'未指定'}[value]||'検証用');
const angleQualityNote=value=>value==='high-latitude'?'／高緯度のため地域角精度に注意':value==='unavailable'?'／極域の地域角は計算対象外':'';
const contributorDetails=item=>(item.details||[]).map(detail=>{
  if(detail.bodies)return`${detail.bodies.join('―')} ${detail.aspectAngle}°／離角 ${detail.separation.toFixed(2)}°／オーブ ${detail.orb.toFixed(2)}°／${motionLabel(detail.motion)}`;
  if(detail.body)return`${detail.body}―${detail.angle}／オーブ ${detail.orb.toFixed(2)}°／${motionLabel(detail.motion)}`;
  return`${detail.phase}側／離角 ${detail.separation.toFixed(2)}°／オーブ ${detail.orb.toFixed(2)}°／${motionLabel(detail.motion)}`;
}).map(text=>`<small>${esc(text)}</small>`).join('');

function shell(events){return `<section class="world-map-shell" id="worldMapShell" aria-labelledby="worldMapTitle"><header class="world-map-head"><div><span class="world-map-kicker">こよみ世情</span><h2 id="worldMapTitle">世界の世情地球儀</h2></div><div class="world-mode" role="group" aria-label="表示モード"><button class="active" data-world-mode="forecast">未来を見る</button><button data-world-mode="validation">過去検証</button></div></header><div class="world-controls"><label>日時<input id="worldDateTime" type="datetime-local" value="${localInputValue(new Date())}"></label><label>テーマ<select id="worldTheme"><option value="earthquake">地震</option><option disabled>火山（準備中）</option><option disabled>気象（準備中）</option><option disabled>戦争・紛争（準備中）</option></select></label><label id="worldEventField" hidden>過去事象<select id="worldEvent">${events.map(item=>`<option value="${item.id}">${esc(item.label)}</option>`).join('')}</select></label></div><div class="world-layer-control"><label for="earthquakeForecastLayer"><span><b>地震予測・研究プレビュー</b><small id="earthquakeForecastLayerState">OFF</small></span><input id="earthquakeForecastLayer" type="checkbox" role="switch" aria-describedby="earthquakeForecastLayerNote"></label><div class="world-preview-selectors"><label class="world-horizon">対象規模<select id="earthquakePreviewMagnitude"><option value="4.5">M4.5以上・活動度</option><option value="6.5" selected>M6.5以上・大地震注意度</option></select></label><label class="world-horizon">horizon<select id="earthquakePreviewHorizon"><option>1</option><option>3</option><option>7</option><option>14</option><option selected>30</option></select>日</label></div><label class="world-outcome-toggle" for="earthquakeOutcomeLayer"><span><b>その後の実績を重ねる</b><small>予測計算には未使用の事後確認データ</small></span><input id="earthquakeOutcomeLayer" type="checkbox" role="switch" checked></label><p id="earthquakeForecastLayerNote">M6.5・30日は開発期間評価済み、M4.5は研究用活動度です。実ホールドアウトは未実施です。</p><div class="world-preview-legend" data-target-magnitude="6.5"><span>低い</span><i></i><i></i><i></i><i></i><span>上位帯</span><b class="world-outcome-key">● 期間内地震</b></div></div><div class="world-map-stage"><div id="worldMap" role="application" aria-label="回転できる世界の世情傾向地球儀"></div><div id="worldMapStatus" class="world-map-status">地球儀を読み込んでいます…</div><button id="worldGlobeReset" class="world-globe-reset" type="button">◎ 地球全体</button></div><p class="world-disclaimer">地球儀をドラッグして地域を選べます。占術・暦等を用いた実験的指標であり、科学的な地震予知ではありません。防災判断では公的機関の情報を優先してください。</p><div class="world-sheet" id="worldSheet" aria-live="polite"><div class="world-sheet-grip"></div><div id="worldSheetBody"><b>地球儀上の地域をタップ</b><p>同じH3セル・日時・テーマで、各占術の反応を比較できます。</p></div></div></section>`}

function visibleCells(map,grid,lockedResolution=null){
  const bounds=map.getBounds(),box={south:bounds.getSouth(),north:bounds.getNorth(),west:bounds.getWest(),east:bounds.getEast()};let resolution=lockedResolution??grid.resolutionForZoom(map.getZoom()),ids=grid.viewportCells(box,resolution,MAX_VISIBLE_CELLS);
  while(ids.length>=MAX_VISIBLE_CELLS&&resolution>0){resolution-=1;ids=grid.viewportCells(box,resolution,MAX_VISIBLE_CELLS)}
  return {ids,resolution};
}

export async function initWorldMap({page,ephemeris,earthquakeForecast}={}){
  if(!page||page.querySelector('#worldMapShell'))return;
  let events=[],preview=null,researchCatalog=null;try{events=await loadEvents()}catch(error){console.error('[WORLD MAP] validation data failed',error)}try{[preview,researchCatalog]=await Promise.all([loadResearchPreview(),loadResearchCatalog()])}catch(error){console.error('[WORLD MAP] preview data failed',error)}
  page.insertAdjacentHTML('afterbegin',shell(events));
  const grid=createSpatialGrid(),adapter=new MundaneEarthquakeAdapter(ephemeris),cache=new WorldEvaluationCache(),status=page.querySelector('#worldMapStatus'),sheet=page.querySelector('#worldSheetBody'),forecastLayer=createForecastLayerState(earthquakeForecast);
  let mode='forecast',forecastLayerOn=false,outcomeLayerOn=true,previewHorizon=30,previewMagnitude=6.5,map,renderToken=0,updateTimer,datedMeta=null,datedRows=new Map(),outcomeEvents=[];const datedCache=new Map();
  const recalculatePreview=()=>{if(!researchCatalog)return;const forecastTime=new Date(page.querySelector('#worldDateTime').value).toISOString(),key=`${forecastTime.slice(0,10)}:${previewMagnitude}:${previewHorizon}`;if(!datedCache.has(key))datedCache.set(key,{preview:calculateDatedPreview(researchCatalog,{forecastTime,targetMagnitude:previewMagnitude,horizonDays:previewHorizon}),outcomes:eventsAfterPreview(researchCatalog,{forecastTime,targetMagnitude:previewMagnitude,horizonDays:previewHorizon})});const cached=datedCache.get(key);datedMeta=cached.preview;datedRows=new Map(datedMeta.rows.map(row=>[String(row.cell_id),row]));outcomeEvents=cached.outcomes};
  const previewRows=()=>datedRows.size?datedRows:new Map((preview?.rows||[]).filter(row=>row.horizon_days===previewHorizon&&row.target_magnitude===previewMagnitude).map(row=>[String(row.cell_id),row]));
  const previewColor=row=>previewMagnitude===4.5?['','#2a9d8f','#3b82b8','#5661b3','#3f2a78'][row?.relative_band]||'#66717f':['','#e0b43b','#e98725','#d94b32','#861f41'][row?.relative_band]||'#66717f';
  const previewRowFor=(cellId,rows=previewRows())=>{const resolution=grid.resolution(cellId);if(resolution===2)return rows.get(String(cellId));if(resolution>2)return rows.get(grid.parent(cellId,2));let selected=null;for(const [id,row] of rows){if(grid.parent(id,resolution)===cellId&&(!selected||row.relative_band>selected.relative_band))selected=row}return selected};
  const outcomesForCell=cellId=>{const resolution=grid.resolution(cellId);return outcomeEvents.filter(item=>resolution===2?item.cell_id===cellId:resolution>2?item.cell_id===grid.parent(cellId,2):grid.parent(item.cell_id,resolution)===cellId)};
  const selectedEvent=()=>events.find(item=>item.id===page.querySelector('#worldEvent')?.value);
  const contextForCell=(cellId)=>{const date=new Date(page.querySelector('#worldDateTime').value);return{datetimeUtc:date.toISOString(),...grid.center(cellId),spatialCellId:cellId,gridSystemId:grid.systemId,gridVersion:grid.version,resolution:grid.resolution(cellId),themeId:'earthquake',mode}};
  const resultForCell=cellId=>cache.evaluate(contextForCell(cellId),adapter);
  const evaluateCell=cellId=>{
    const center=grid.center(cellId),result=resultForCell(cellId),event=mode==='validation'?selectedEvent():null,relation=event?relateEventToCell(event,cellId,grid):null;
    const forecastRow=previewRowFor(cellId),cellOutcomes=outcomesForCell(cellId),maximumMagnitude=cellOutcomes.length?Math.max(...cellOutcomes.map(item=>item.magnitude)):null,relativeLabel=['','低い','中間','比較的高い','上位帯'][forecastRow?.relative_band]||'データ不足',magnitudeLabel=previewMagnitude===4.5?'M4.5以上・活動度':'M6.5以上・大地震注意度';
    sheet.innerHTML=`<div class="world-sheet-title"><div><small>地震テーマ・マンデン</small><h3>${center.latitude.toFixed(2)}°, ${center.longitude.toFixed(2)}°</h3></div><strong style="color:${color(result.score)}">${result.metadata.calculationQuality==='unavailable'?'計算データ不足':level(result.score)}</strong></div><p><b>${result.consensus.matched} / ${result.consensus.total} 系統一致</b></p>${event?`<div class="world-event-detail"><b>${esc(event.label)} M${event.magnitude.toFixed(1)}</b><span>深さ ${event.depthKm}km</span><span>セル中心まで ${relation.centerDistanceKm.toFixed(1)}km</span><span>${relation.sameCell?'震源と同じセル':relation.ring===null?'5近傍より外側':`${relation.ring}近傍セル`}</span><a href="${esc(event.source.url)}" target="_blank" rel="noopener">${esc(event.source.name)}で確認</a></div>`:''}<section class="world-forecast-detail" aria-label="地震予測機能の状態"><div><span>地震予測機能</span><b>研究プレビュー・検証中</b></div><div><span>対象規模</span><b>${magnitudeLabel}</b></div><div><span>使用モデル</span><b>${esc(preview?.modelNames?.[String(previewMagnitude)]||preview?.modelName||forecastLayer.modelName)}</b></div><div><span>選択horizon</span><b>${previewHorizon}日</b></div><div><span>相対区分</span><b>${esc(relativeLabel)}</b></div><div><span>計算基準日</span><b>${esc(datedMeta?.calculationTimeUtc?.slice(0,10)||preview?.forecastTimeUtc?.slice(0,10)||'未取得')}</b></div><div><span>カタログ収録終了</span><b>${esc(researchCatalog?.freshness?.catalogThroughUtc?.slice(0,16)?.replace('T',' ')||'未取得')} UTC</b></div><div><span>最終更新成功</span><b>${esc(researchCatalog?.freshness?.lastSuccessfulUpdateUtc?.slice(0,16)?.replace('T',' ')||'未取得')} UTC</b></div><div><span>完全性確認</span><b>${researchCatalog?.freshness?.complete?'正常':'未確認'}</b></div><div><span>期間内の実績</span><b>${cellOutcomes.length}件${maximumMagnitude?`・最大M${maximumMagnitude.toFixed(1)}`:''}</b></div><div><span>最初の発生日</span><b>${cellOutcomes[0]?.time_utc?.slice(0,10)||'該当なし'}</b></div><div><span>実ホールドアウト</span><b>未実施</b></div><div><span>データ品質</span><b>${forecastRow?`${Math.round(forecastRow.data_quality*100)} / 100`:'データ不足'}</b></div><p>${datedMeta?.futureDateClamped?'選択日はカタログ最終日より未来のため、取得済み最終日で計算しています。':'選択日より前の地震だけで再計算しています。期間内の実績は予測計算に使用していない事後確認データです。'} 防災判断には使用できません。</p></section><div class="world-contributors">${result.contributors.map(item=>`<div><span>${esc(item.label)}</span><b>${contributorState(item)}</b><small>${esc(item.reason)}</small>${contributorDetails(item)}</div>`).join('')}</div><details><summary>詳しい根拠</summary><p>ルール ${esc(result.version)}／H3 ${esc(grid.version)}／解像度 ${result.resolution}／確度: 実験段階</p><p>天文計算 ${esc(ephemerisLabel(result.metadata))}／精度 ${esc(precisionLabel(result.metadata.ephemerisPrecision))}／計算品質 ${esc(calculationQualityLabel(result.metadata.calculationQuality))}${esc(angleQualityNote(result.metadata.angleQuality))}</p><p>カタログ入力SHA-256 ${esc(researchCatalog?.inputSha256||'未取得')}</p><p>異なる占術のスコアは加算していません。セル関係は的中判定ではありません。</p></details>`;
    return result;
  };
  const updateEventMarker=()=>{if(!map?.isStyleLoaded())return;const event=mode==='validation'?selectedEvent():null,data={type:'FeatureCollection',features:event?[{type:'Feature',properties:{label:event.label,magnitude:event.magnitude},geometry:{type:'Point',coordinates:[event.longitude,event.latitude]}}]:[]};const source=map.getSource('validation-event');if(source)source.setData(data);else{map.addSource('validation-event',{type:'geojson',data});map.addLayer({id:'validation-event-dot',type:'circle',source:'validation-event',paint:{'circle-radius':8,'circle-color':'#fff','circle-stroke-width':4,'circle-stroke-color':'#b42318'}})}};
  const updateOutcomeMarkers=()=>{if(!map?.isStyleLoaded())return;const active=mode==='forecast'&&forecastLayerOn&&outcomeLayerOn,data={type:'FeatureCollection',features:active?outcomeEvents.map(item=>({type:'Feature',properties:{magnitude:item.magnitude,timeUtc:item.time_utc},geometry:{type:'Point',coordinates:[item.longitude,item.latitude]}})):[]},source=map.getSource('forecast-outcomes');if(source)source.setData(data);else{map.addSource('forecast-outcomes',{type:'geojson',data,cluster:true,clusterRadius:32,clusterMaxZoom:6});map.addLayer({id:'forecast-outcome-clusters',type:'circle',source:'forecast-outcomes',filter:['has','point_count'],paint:{'circle-radius':['step',['get','point_count'],12,25,17,100,22],'circle-color':'#fff7dc','circle-stroke-width':2,'circle-stroke-color':'#d11f3a','circle-opacity':.9}});map.addLayer({id:'forecast-outcome-cluster-count',type:'symbol',source:'forecast-outcomes',filter:['has','point_count'],layout:{'text-field':['get','point_count_abbreviated'],'text-size':11},paint:{'text-color':'#5e1020'}});map.addLayer({id:'forecast-outcome-dots',type:'circle',source:'forecast-outcomes',filter:['!', ['has','point_count']],paint:{'circle-radius':['interpolate',['linear'],['get','magnitude'],4.5,4,6.5,8,8,12],'circle-color':'#fff7dc','circle-stroke-width':2,'circle-stroke-color':'#d11f3a','circle-opacity':.94}})}};
  const update=()=>{
    if(!map?.isStyleLoaded())return;const token=++renderToken,{ids,resolution}=visibleCells(map,grid,forecastLayerOn?2:null),started=performance.now(),features=[];
    for(const id of ids){if(token!==renderToken)return;const result=resultForCell(id);features.push({id,result})}
    const rows=previewRows(),featureMap=new Map(features.map(item=>[item.id,item.result])),data=grid.geoJson(features.map(item=>item.id),id=>{const result=featureMap.get(id),row=previewRowFor(id,rows);return{score:result.score,matched:result.consensus.matched,forecastLayerActive:forecastLayerOn,previewBand:forecastLayerOn&&row?row.relative_band:0,previewColor:previewColor(row)}}),source=map.getSource('world-grid');
    if(source)source.setData(data);else{map.addSource('world-grid',{type:'geojson',data,maxzoom:14});map.addLayer({id:'world-grid-fill',type:'fill',source:'world-grid',paint:{'fill-color':['case',['get','forecastLayerActive'],['get','previewColor'],['step',['get','score'],'#1e7f68',40,'#d9a514',70,'#e46f19',80,'#b42318']],'fill-opacity':['interpolate',['linear'],['zoom'],0,['case',['get','forecastLayerActive'],.48,.3],10,['case',['get','forecastLayerActive'],.4,.25],14,['case',['get','forecastLayerActive'],.34,.22]]}});map.addLayer({id:'world-grid-line',type:'line',source:'world-grid',paint:{'line-color':'#fff','line-opacity':['interpolate',['linear'],['zoom'],0,.48,10,.38,14,.3],'line-width':['interpolate',['linear'],['zoom'],0,1,10,.7,14,.5]}})}
    updateEventMarker();updateOutcomeMarkers();status.textContent=`H3 解像度 ${resolution}・表示セル ${ids.length}・期間内地震 ${outcomeLayerOn?outcomeEvents.length:0}件・${Math.round(performance.now()-started)}ms`;
  };
  const scheduleUpdate=()=>{clearTimeout(updateTimer);updateTimer=setTimeout(update,180)};
  const layerToggle=page.querySelector('#earthquakeForecastLayer'),outcomeToggle=page.querySelector('#earthquakeOutcomeLayer'),horizonSelect=page.querySelector('#earthquakePreviewHorizon'),magnitudeSelect=page.querySelector('#earthquakePreviewMagnitude');recalculatePreview();layerToggle.onchange=()=>{forecastLayerOn=layerToggle.checked;page.querySelector('#earthquakeForecastLayerState').textContent=forecastLayerOn?'研究プレビュー・検証中':'OFF';scheduleUpdate()};outcomeToggle.onchange=()=>{outcomeLayerOn=outcomeToggle.checked;scheduleUpdate()};horizonSelect.onchange=()=>{previewHorizon=Number(horizonSelect.value);recalculatePreview();scheduleUpdate()};magnitudeSelect.onchange=()=>{previewMagnitude=Number(magnitudeSelect.value);page.querySelector('.world-preview-legend').dataset.targetMagnitude=String(previewMagnitude);page.querySelector('#earthquakeForecastLayerNote').textContent=previewMagnitude===4.5?'M4.5以上の地震活動度です。実ホールドアウト未実施・防災判断には使用できません。':'M6.5・30日は開発期間評価済みです。実ホールドアウト未実施・防災判断には使用できません。';recalculatePreview();scheduleUpdate()};
  page.querySelectorAll('[data-world-mode]').forEach(button=>button.onclick=()=>{mode=button.dataset.worldMode;cache.clear();page.querySelectorAll('[data-world-mode]').forEach(item=>item.classList.toggle('active',item===button));page.querySelector('#worldEventField').hidden=mode!=='validation';if(mode==='validation'&&events.length){const event=selectedEvent();page.querySelector('#worldDateTime').value=localInputValue(event.datetimeUtc);map?.flyTo({center:[event.longitude,event.latitude],zoom:5});evaluateCell(grid.cellForLatLng(event.latitude,event.longitude,grid.resolutionForZoom(5)))}else page.querySelector('#worldDateTime').value=localInputValue(new Date());scheduleUpdate()});
  const eventSelect=page.querySelector('#worldEvent');if(eventSelect)eventSelect.onchange=()=>{const event=selectedEvent();page.querySelector('#worldDateTime').value=localInputValue(event.datetimeUtc);map?.flyTo({center:[event.longitude,event.latitude],zoom:5});evaluateCell(grid.cellForLatLng(event.latitude,event.longitude,grid.resolutionForZoom(5)));scheduleUpdate()};
  try{
    const mapElement=page.querySelector('#worldMap'),initialZoom=globeZoomFor(mapElement),maplibre=await loadMapLibre();map=new maplibre.Map({container:'worldMap',style:createOfflineWorldStyle(),center:GLOBE_CENTER,zoom:initialZoom,minZoom:0,maxZoom:14,attributionControl:true});map.addControl(new maplibre.NavigationControl({showCompass:false}),'top-right');
    const ensureGlobe=()=>{map.setProjection({type:'globe'});const projection=map.getProjection();if(projection?.type!=='globe')throw new Error('globe projection unavailable');return projection};
    const resetGlobe=()=>{try{ensureGlobe();map.easeTo({center:GLOBE_CENTER,zoom:globeZoomFor(mapElement),pitch:0,bearing:0,duration:650})}catch(error){console.error('[WORLD MAP] globe reset failed',error);status.textContent='この端末では地球儀表示を利用できません。'}};
    map.on('style.load',()=>{try{ensureGlobe()}catch(error){console.error('[WORLD MAP] globe activation failed',error);status.textContent='この端末では地球儀表示を利用できません。'}});map.on('load',()=>{ensureGlobe();update()});map.on('moveend',scheduleUpdate);map.on('click',event=>evaluateCell(grid.cellForLatLng(event.lngLat.lat,event.lngLat.lng,forecastLayerOn?2:grid.resolutionForZoom(map.getZoom()))));page.querySelector('#worldGlobeReset').onclick=resetGlobe;page.querySelector('#worldDateTime').onchange=()=>{cache.clear();recalculatePreview();scheduleUpdate()};
  }catch(error){status.textContent='基本世界地図を読み込めませんでした。H3計算と保存済み過去事象は利用できます。';sheet.innerHTML='<b>地図を読み込めませんでした</b><p>アプリをオンラインで一度開いて基本地図を保存してください。既存の世情鑑定と研究結果はこの下で利用できます。</p>'}
}
