(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.KOYOMI_PERSONA_ADAPTER = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  const BANK = {
    warm: ['まぁ、よくここまで一人で抱えてきたわね。まず深呼吸なさい。','あら、話してくれてよかった。気持ちも現実も、両方置いていかないわよ。','そうなのね。アンタが頑張った分まで、なかったことにはしないわ。','うん、迷うのも無理ないわ。今日は絡まった糸を一本ずつほどきましょう。','いらっしゃい。格好つけなくていいの、今の本音から見ていくわよ。','大丈夫、甘やかしはしないけど一人にもさせないわ。順番に見ましょう。'],
    bright: ['あら、悪くないじゃない。追い風を雑に使わなければ、ちゃんと伸びるわよ。','まぁ素敵。扉は開いてるわ、あとはハイヒールで駆け込まないことね。','いい顔して。今回は遠慮より、準備した一歩がものを言うわ。','あらやだ、運がせっかく合図してるのに見ないふりは野暮よ。','今回は希望だけじゃないわ。現実にも動かせる余白があるの。','そうそう、その調子。ただし景気よく約束まで増やしちゃ駄目よ。'],
    firm: ['アンタね、ここは曖昧な笑顔で通り過ぎちゃ駄目。結論から言うわ。','ちょっと耳が痛いわよ。でも、傷を広げないために言うの。','今日は綺麗事を脱いで。見るのは願望じゃなく、条件と行動よ。','いい？ 運命のせいにする前に、止めるべきものを止めるわよ。','あら、そこを誤魔化したら姐さんの三つ目が黙ってないわ。','はっきり言うわ。今必要なのは勇気より、確認と境界線よ。'],
    bridge: ['でね、ここからが大事。','さて、気持ちは分かった。次は現実を見ましょう。','ほら、点数よりこっちを見て。','つまりね、話を難しくしなくていいの。','ここで一度、足元へ戻るわよ。','じゃあ、アンタが今日動かせる所まで降ろしましょう。'],
    aside: ['運は便利だけど、丸投げされたら運だって困るのよ。','愛も仕事も、察して大会を始めたらだいたい迷子よ。','勢いは口紅と同じ。効くけど、塗りすぎると話が入ってこないの。','「いつか」は予定表に載らないの。日付を決めてちょうだい。','全部やるは、だいたい全部ぼやけるのよ。一つに絞りなさい。','奇跡待ちも悪くないけど、その間に確認の電話一本くらいできるわ。'],
    close: ['アンタなら選び直せるわ。今日はその証拠を一つ作っておいで。','泣いても迷ってもいい。でも、自分を雑に扱う選択だけはしないで。','運は判決じゃないの。使い方を決めるのは、最後までアンタよ。','ほら、胸を張って。一歩は小さく、条件は具体的に。それで十分よ。','姐さんは背中を押すけど、崖には押さないわ。確かめてから進みなさい。','また迷ったら、気分じゃなく変わった事実を持っていらっしゃい。'],
    safeClose: ['今は一人で結論を背負わないで。安全を確保し、信頼できる人や専門窓口へつないで。','占いより安全が先よ。距離を取り、記録を残し、第三者の力を借りなさい。','無理に強くならなくていい。危険から離れることが、今日の正解よ。']
  };
  function hash(text){let value=2166136261;for(const ch of String(text||''))value=Math.imul(value^ch.charCodeAt(0),16777619);return value>>>0}
  function pick(list,seed,offset){return list[((hash(seed)+offset*2654435761)>>>0)%list.length]}
  function topic(question){const cleaned=String(question||'').replace(/[\n\r。、！？!?「」『』（）()]/g,' ').replace(/\s+/g,' ').trim();if(!cleaned)return'';const words=cleaned.match(/[一-龠ぁ-んァ-ヶーA-Za-z0-9]{2,18}/g)||[];const ignored=/^(について|どうしたら|でしょうか|したいです|知りたい|お願いします|できる|こと|もの|ため)$/;return words.find(word=>!ignored.test(word))||words[0]||''}
  function build(input){const score=Number(input.score)||50,risk=Math.max(Number(input.risk)||0,Number(input.psychRisk)||0),mode=input.mode==='zubat'?'zubat':'sister',evidence=(input.evidence||input.reasons||[]).filter(Boolean),focus=evidence[0]||`${input.system||'総合鑑定'} ${score}点`,seed=[input.system,score,mode,evidence.join('|'),input.action,input.variant||0].join('|'),serious=risk>=70,openingBank=serious||mode==='zubat'||score<42?BANK.firm:score>=68?BANK.bright:BANK.warm;return{opening:pick(openingBank,seed,1),address:`今回は「${focus}」を軸に、出た結果を現実の動きへ訳すわよ。`,bridge:pick(BANK.bridge,seed,2),aside:serious?'':pick(BANK.aside,seed,3),closing:serious?pick(BANK.safeClose,seed,4):pick(BANK.close,seed,4),tone:serious?'safety':mode==='zubat'?'direct':score>=68?'bright':'warm',focus,serious}}
  function apply(text,input){const layer=build(input);let output=String(text||'');output=output.replace('【結論】\n',`【結論】\n${layer.opening}\n${layer.address}\n`);output=output.replace('【何が起こりそうか】\n',`【何が起こりそうか】\n${layer.bridge}\n`);if(layer.aside)output=output.replace('【避ける行動】\n',`【姐さんのひと言】\n${layer.aside}\n\n【避ける行動】\n`);output=output.replace(/【最後の一言】\n[\s\S]*$/,`【最後の一言】\n${layer.closing}`);return{text:output,persona:layer}}
  function conversationalize(text){return String(text||'').replace(/してください。/g,'してちょうだい。').replace(/してください/g,'してちょうだい').replace(/必要があります。/g,'必要があるわ。').replace(/優先します。/g,'優先するの。').replace(/扱います。/g,'扱うわ。').replace(/使います。/g,'使うの。').replace(/保証しません。/g,'保証しないわ。').replace(/決めません。/g,'決めないわ。').replace(/でしょう。/g,'でしょうね。').replace(/です。/g,'よ。')}
  const DOMAINS={四柱推命:['役割と責任','仕事量・体調・対人反応','30日'],宿曜:['距離感と連絡','返信頻度・会う約束・境界線','14日'],九星気学:['環境と段取り','予定の遅れ・片付け・移動負担','9日'],西洋占星術:['心理と時期','感情の波・注目される領域・予定変更','14日'],タロット:['目前の選択','相手の反応・障害の再発・結果へ向かう変化','7日'],ルーン:['最初の一手','連絡・決断・中断した作業の動き','3日'],姓名判断:['社会での役割','呼ばれ方・任され方・対人印象','30日'],数秘術:['繰り返す行動','着手数・完了数・生活リズム','14日'],カバラ:['名前と約束','名乗った役割と実際の行動の一致','30日'],六星周期:['実行量と休止','新規件数・未完了件数・疲労','12日'],大運・暦:['長期方針と実行日','進捗・負担・残高・予定変更','30日']};
  const PLAYBOOKS={四柱推命:['予定表を開き、今日の依頼を「自分で行う・人に頼む・断る」の三列へ一件ずつ分ける','担当者・期限・終わりの状態を一行にする'],宿曜:['相手との直近三件のやり取りから、日付のある約束と未返信を一件ずつ抜き出す','次に連絡する日と返答を待つ時刻を決める'],九星気学:['出発15分前に経路・所要時間・遅れた時の連絡先を画面に出す','予定へ30分の予備時間を入れる'],西洋占星術:['スマホのメモへ「起きた事実・感じたこと・次にすること」を一行ずつ書く','三行目を今日中にできる一動作にする'],タロット:['紙を二列に分け、カードが示す注意と現実に確認できた事実を一つずつ書く','24時間以内に確認する相手・数字・期限のどれか一つを丸で囲む'],ルーン:['受信箱か未完了一覧から15分で動かせる一件を選び、送信・再開・中止のどれかを行う','実行後に時刻と結果を一行残す'],姓名判断:['実際の署名・肩書き・自己紹介を並べ、表記が違う箇所を一つ直す','相手に覚えてほしい役割を十五文字以内で統一する'],数秘術:['今日の予定を「始めた・終えた・残した」の三つに数え分ける','明日へ残す項目を三件以内にする'],カバラ:['署名と予定表を開き、今日名乗っている役割と実際の行動を一つずつ書く','役割に合わない予定を一件外す'],六星周期:['未完了一覧から最も期限が近い一件を選び、新規申込みより先に閉じる','完了時刻を記録してから次の作業を始める'],'大運・暦':['今日と30日後の予定表を並べ、長期方針を変えず実行日だけ調整する','期限・費用上限・取り消せる最終日を記録する'],総合鑑定:['予定表を開き、今日中に確認できる一件へ「誰が・何を・何時まで」を書く','完了か保留かを今日の終了時に記録する']};
  function concreteScenario(input){const system=input.system||'総合鑑定',domain=DOMAINS[system]||['生活の優先順位','進捗・負担・相手の行動','14日'],playbook=PLAYBOOKS[system]||PLAYBOOKS.総合鑑定,score=Number(input.score)||50,evidence=(input.evidence||input.reasons||[]).filter(Boolean).slice(0,2),requested=String(input.action||'').trim(),action=`${requested?`${requested}。そのうえで、`:''}${playbook[0]}`,state=score>=68?'前進':score<45?'防御':'試行',scene=state==='前進'?`今日の${domain[0]}では、すでに決まっている一件を動かせる。増やすのは一件までにして、${playbook[1]}`:state==='防御'?`今日の${domain[0]}では、返信の遅れ・予定超過・疲労のどれかを先に確認する。新しい約束は増やさず、${playbook[1]}`:`今日の${domain[0]}では、一件だけ試して結果を記録する。続行を先に決めず、${playbook[1]}`,go=state==='前進'?`担当者・期限・費用上限が書けて、${playbook[1]}こと`:state==='防御'?`不足情報が埋まり、睡眠時間や残高を減らさず、${playbook[1]}こと`:`七日以内に結果を数えられ、元の状態へ戻せて、${playbook[1]}こと`,stop='支払額の増加、期限超過、約束違反、睡眠が普段より二時間以上短い状態のどれか一つが出た時',why=evidence.length?evidence.join('／'):`${system}の信号${score}`;return{state,scene,why,action,observable:domain[1],go,stop,review:domain[2]}}
  function scenarioText(s){return`【現実に出やすい形】\n${s.scene}わ。見る数字は「${s.observable}」。\n\n【進める条件】\n${s.go}。最初にするのは「${s.action}」よ。\n\n【止める条件】\n${s.stop}は中止して確認。運の点数より、この条件を優先なさい。\n\n【再確認】\n${s.review}後に「始めた数・終えた数・負担・相手の行動」から二項目を比べるの。変化がなければ、根性ではなく方法を変えなさい。`}
  function applyDivination(text,input){const layer=build(input),scenario=concreteScenario(input),renderer=globalThis.KOYOMI_PERSONA_RENDERER,evidence=(input.evidence||[]).filter(Boolean).slice(0,2),level=input.level||globalThis.document?.getElementById('readingModeSetting')?.value||'standard',legacy=String(text||'').replace(/相談「[^」]*」を、?/g,'').replace(/相談「[^」]*」/g,'').replace(/【相談と([^】]+)】/g,'【$1の鑑定結果】').replace(/【相談への回答】/g,'【鑑定結果からの結論】');if(renderer){const rendered=renderer.render({system:input.system||'この占術',opening:level==='beginner'?'難しい言葉は抜きで、先に使い方を話すわね。':layer.opening,axis:layer.address,result:scenario.scene,scenario,evidence,closing:layer.closing},{voice:input.mode==='zubat'?'zubat':'sister',level});return{text:level==='beginner'?rendered:`${rendered}\n\n【詳しい鑑定資料】\n${legacy}`,persona:layer,scenario,level}}return{text:`${layer.opening}\n\n${scenarioText(scenario)}\n\n${legacy}\n\n${layer.closing}`,persona:layer,scenario,level}}
  return{BANK,DOMAINS,PLAYBOOKS,build,apply,applyDivination,concreteScenario,scenarioText,conversationalize,topic};
});
